# Entry definitions. Every "q" (quote) must be an exact substring of the Rishon text
# as fetched; every "anchor" must occur (nikud-insensitive) in the cited liturgy segment.
# Labels in Hebrew are descriptive; source text is never typed by hand here, only located.

SECTIONS = [
    ("torah", 'רש"י על התורה'),
    ("nach", 'רש"י על נביאים וכתובים'),
    ("shas", 'רש"י על הש"ס'),
    ("tosafos", "תוספות"),
]

# Liturgy sources: key -> (sefaria ref, Hebrew label, nusach label)
LIT = {
    "shekalim": ("Siddur Sefard, Yotzerot, Parashat Sekalim", "יוצר לפרשת שקלים", "סידור ספרד (תורת אמת)"),
    "zachor": ("Siddur Sefard, Yotzerot, Parashat Zachor", "יוצר לפרשת זכור", "סידור ספרד (תורת אמת)"),
    "parah": ("Siddur Sefard, Yotzerot, Parashat Parah", "יוצר לפרשת פרה", "סידור ספרד (תורת אמת)"),
    "hagadol": ("Siddur Sefard, Yotzerot, Shabbat HaGadol", "יוצר לשבת הגדול", "סידור ספרד (תורת אמת)"),
    "rh1": ("The Koren Rosh HaShana Mahzor; Ashkenaz, First Day, Leader's Repetition for Shaharit",
            "חזרת הש\"ץ לשחרית, יום א' של ראש השנה", "מחזור קורן, נוסח אשכנז"),
    "selichot2": ("Selichot Nusach Ashkenaz Lita, Second Day of the Ten Days of Penitence 4",
                  "סליחות, יום ב' של עשרת ימי תשובה", "סליחות נוסח ליטא"),
    "esther": ("Siddur Ashkenaz, Festivals, Selichot, Fast of Esther", "סליחות לתענית אסתר", "סידור אשכנז (דעת)"),
    "hachodesh": ("Siddur Sefard, Yotzerot, Parashat HaChodesh", "יוצר לפרשת החודש", "סידור ספרד (תורת אמת)"),
    "yotzer_or": ("Siddur Ashkenaz, Weekday, Shacharit, Blessings of the Shema, First Blessing before Shema", "ברכת יוצר אור, שחרית של חול", "סידור אשכנז (מצודה)"),
    "rh1_musaf": ("Machzor Rosh Hashanah Sefard, Musaf, First Day of Rosh Hashana, Reader's Repetition", "חזרת הש\"ץ למוסף, יום א' של ראש השנה", "מחזור ראש השנה (נוסח ספרד)"),
    "rh2_musaf": ("Machzor Rosh Hashanah Sefard, Musaf, Second Day of Rosh Hashana, Reader's Repetition 166-180", "זכרונות, חזרת הש\"ץ למוסף, יום ב' של ראש השנה", "מחזור ראש השנה (נוסח ספרד)"),
    "selichot_polin5": ("Selichot Nusach Polin, Fifth Day of the Ten Days of Penitence 7", "סליחות, יום ה' של עשרת ימי תשובה", "סליחות נוסח פולין"),
    "kinot11": ("Kinnot for Tisha B'Av (Ashkenaz), Kinot for Tisha B'Av Day 11", "קינה: איכה אלי קוננו מאליו", "קינות לתשעה באב, נוסח אשכנז"),
    "kinot24": ("Kinnot for Tisha B'Av (Ashkenaz), Kinot for Tisha B'Av Day 24", "קינה: תסתר לאלם תרשישים מרון", "קינות לתשעה באב, נוסח אשכנז"),
}
# Keys beginning with w_ are Wikisource pages, defined in tools/wiki_lit.py (built into wiki_lit.json).

# kind: "line" = quotes the piyut's words; "content" = cites the piyut's content without quoting a line
# lit: list of (source key, anchor text found in the liturgy, note or None)
# said: where it is said, with basis: ("text", ...) taken from the found liturgy;
#       ("rishon", ...) stated by the Rishon himself; ("other", ref, text) another source; None = not stated
E = [
 # ---------------- Rashi on Torah
 dict(sec="torah", ref="Rashi on Genesis 30:22:1", label='רש"י בראשית ל:כב', paytan="הפייט",
      q=["הָאַדְמוֹן כְּבָט שֶׁלֹּא חָלָה, צָבָה לְקַחְתָּהּ לוֹ וְנִתְבֶּהָלָה"], kind="line",
      lit=[("rh1", "האדמון כבט שלא חלה", None)]),
 dict(sec="torah", ref="Rashi on Exodus 26:15:1", label='רש"י שמות כו:טו', paytan="הבבלי",
      q=["טָס מַטַּע מְזֹרָזִים קוֹרוֹת בָּתֵּינוּ אֲרָזִים"], kind="line",
      lit=[("w_oryesha", "טס מטע מזורזים", None)]),
 # ---------------- Rashi on Nach
 dict(sec="nach", ref="Rashi on Ezekiel 21:18:3", label='רש"י יחזקאל כא:יח', paytan="הפייט",
      q=["הַמּוֹאֶסֶת כָּל עֵץ הִדְקִיר הַמְּזַנֶּה"], kind="line",
      lit=[("w_odecha", "הדקיר המזנה", "בנוסח ויקיטקסט: \"מֹאֶסֶת כָּל עֵץ\"; רש\"י: \"הַמּוֹאֶסֶת\".")],
      said=("rishon", "בַּחֲנֻכָּה (בשבת ראשונה ביוצר)")),
 dict(sec="nach", ref="Rashi on Lamentations 1:6:2", label='רש"י איכה א:ו', paytan="הפייט",
      q=["מָלֵא רֻדַּפְתִּי וְחָסְרָה שְׁנַת גְּאוּלַי"], kind="line",
      lit=[("selichot2", "מלא רדפתי וחסרה שנת גאולי", None)]),

 dict(sec="nach", ref="Rashi on Isaiah 6:3:1", label='רש"י ישעיה ו:ג', paytan="",
      q=["קְדוּשָׁה כֻּלָּם כְּאֶחָד עוֹנִים"], kind="line",
      lit=[("yotzer_or", "קדשה כלם כאחד עונים", None)], said=("rishon", "בְּיוֹצֵר אוֹר")),
 dict(sec="nach", ref="Rashi on Isaiah 24:22:3", label='רש"י ישעיה כד:כב', paytan="הקלירי",
      q=["לְרֹב יָמִים לְהִמָּנוֹת, לַחְשׁוֹב לָהֶם חֶשְׁבּוֹנוֹת"], kind="line",
      lit=[("zachor", "לרוב ימים להמנות", None)], said=("editor", "בסלוק של יוצר דפרשת זכור")),
 dict(sec="nach", ref="Rashi on II Kings 11:2:1", label='רש"י מלכים ב יא:ב', paytan="רבי אליעזר",
      q=["נִפֵּץ חֲדַר הַמִּטּוֹת, חָרְבַּן בֵּיתְךָ יְכַפֵּר עֲלֵיהֶם"], kind="line",
      lit=[("rh1_musaf", "נפץ חדר המטות", "בנוסח המחזור: \"אם פץ להמטות נפץ חדר המטות לכפור יזכר\"")]),
 dict(sec="nach", ref="Rashi on Ezekiel 42:20:1", label='רש"י יחזקאל מב:כ', paytan="הקלירי",
      q=["דָּוִד יִנְטֶה קַו שְׁלֹשֶׁת אַלְפֵי אַמּוֹת קְצוּבָה עַל שְׁלֹשֶׁת אַלְפֵי אַמּוֹת", "שְׁלֹשִׁים וְשִׁשָּׁה כְּמוֹ שֶׁהָיְתָה מִתְכַּפֶּלֶת"], kind="line",
      lit=[("w_erchatz", "שלשים וששה כמו שהיתה מתכפלת", None), ("w_erchatz", "דוד ינטה קו", None)], said=("editor", "בקדשתא דיום שני של סכות")),
 dict(sec="nach", ref="Rashi on Ezekiel 43:3:1", label='רש"י יחזקאל מג:ג', paytan="הפייט",
      q=["מַחֲזוֹת הַמְצֻחְצָחוֹת בְּתֵשַׁע מַחֲזוֹת"], kind="line",
      lit=[("w_erchatz", "במחזות המצחצחות בתשע מחזות", None)], said=("editor", "שם בסלוק")),
 dict(sec="nach", ref="Rashi on Ezekiel 48:1:3", label='רש"י יחזקאל מח:א', paytan="רבי אלעזר",
      q=["לְעֵת חִלּוּק אַרְצוֹתֶיהָ, כְּשׁוּרַת הַכֶּרֶם לְחוּצוֹתֶיהָ"], kind="line",
      lit=[("w_erchatz", "לעת חלוק ארצותיה", "בנוסח ויקיטקסט ההמשך: \"כְּשׁוּרוֹת הַכֶּרֶם לְחַבְּרָם לְתוֹצְאוֹתֶיהָ\"; רש\"י: \"כשורת הכרם לחוצותיה\".")],
      said=("rishon", "בְּפִיּוּט כִּי אֶקַּח מוֹעֵד (בסלוק דיום שני של סכות)")),
 dict(sec="nach", ref="Rashi on Psalms 42:5:4", label='רש"י תהלים מב:ה', paytan="הפייט",
      q=["הָמוֹן חוֹגֵג וְשׁוֹטֵף כַּנָּהָר"], kind="line",
      lit=[("shekalim", "המון חוגג שוטף כנהר", "בנוסח הסידור: \"המון חוגג שוטף כנהר\", בלי וי\"ו.")],
      said=("editor", "בשחרית פרשת שקלים ביוצר של אלה אזכרה")),
 dict(sec="nach", ref="Rashi on Psalms 121:1:2", label='רש"י תהלים קכא:א', paytan="הקליר",
      q=["וּמִתַּחְתֶּיהָ שְׁלֹשִׁים מַעֲלוֹת, זוֹ לְמַעְלָה מִזּוֹ עַד כִּסֵּא הַכָּבוֹד טָסוֹת וְעוֹלוֹת"], kind="line",
      lit=[("w_erchatz", "ומתחתיהם שלשים מעלות", "רש\"י מקצר: בסלוק \"וּמִתַּחְתֵּיהֶם שְׁלֹשִׁים מַעֲלוֹת ... וְעַל גַּבָּם שִׁשִּׁים מַעֲלוֹת, זוֹ לְמַעְלָה מִזּוֹ עוֹלוֹת, וְעַד כִּסֵּא הַכָּבוֹד טָסוֹת וְעוֹלוֹת\".")],
      said=("editor", "בסילוק דיוצר של יום ב׳ דסוכות")),
 dict(sec="nach", ref="Rashi on Song of Songs 4:10:1", label='רש"י שיר השירים ד:י', paytan="הבבלי",
      q=["מְנוּחָה וּשְׁאָר וִעוּדִים"], kind="line", lit=[("w_oryesha", "מנוחה ושאר ועודים", None)]),
 dict(sec="nach", ref="Rashi on Lamentations 3:20:1", label='רש"י איכה ג:כ', paytan="הפייט",
      q=["בְּזֹאת יָדַעְתִּי כִּי יֵשׁ לְךָ לִזְכּוֹר, אֲבָל תָּשׁוֹחַ עָלַי נַפְשִׁי עַד שֶׁתִּזְכּוֹר"], kind="line",
      lit=[("zachor", "בזאת ידעתי כי יש לך לזכור", None)]),
 dict(sec="nach", ref="Rashi on Zechariah 5:11", sub=(2,), label='רש"י זכריה ה:יא', paytan="הקלירי",
      q=["רְבִיעִית הִיא שְׁמִינִית"], kind="line", lit=[]),
 dict(sec="nach", ref="Rashi on Daniel 8:14:2", label='רש"י דניאל ח:יד', paytan="רבי אלעזר הקליר",
      q=["שְׁבוּעִים שִׁשָּׁה"], kind="line",
      lit=[("hachodesh", "ויתכסה מהם שבעים", "בנוסח הסידור שבספריא: \"שבעים שבעה\". רש\"י מביא \"שבועים ששה\".")],
      said=("editor", "בסלוק יוצר של פרשת החדש")),
 dict(sec="nach", ref="Rashi on Daniel 12:12:1", label='רש"י דניאל יב:יב', paytan="רבי אליעזר הקליר",
      q=["וְיִתְכַּסֶּה מֵהֶם שְׁבוּעִים שִׁשָּׁה"], kind="line",
      lit=[("hachodesh", "ויתכסה מהם שבעים", "בנוסח הסידור שבספריא: \"שבעים שבעה\". רש\"י מביא \"שבועים ששה\".")],
      said=("editor", "בסלוק יוצר פרשת החדש")),
 dict(sec="nach", ref="Rashi on I Chronicles 25:3:1", label='פירוש המיוחס לרש"י, דה"י א כה:ג', paytan="הפייטן",
      q=["רָשׁוּם מִבֶּטֶן לְהִפָּקֵד בְּמִשְׁמֶרֶת הַקֹּדֶשׁ"], kind="line",
      lit=[("shekalim", "רשום מבטן להפקד במשמרת הקדש", None)], said=("editor", "בקדשת של יוצר דפרשת שקלים")),
 dict(sec="nach", ref="Rashi on I Chronicles 28:9:1", label='פירוש המיוחס לרש"י, דה"י א כח:ט', paytan="הפייט",
      q=["שְׁנֵי לְבָבוֹת לְךָ כְּאֶחָד לְאֶחָד"], kind="line",
      lit=[("rh1_musaf", "שני לבבות לך כאחד לאחד", None)], said=("editor", "בקדושתא דמוסף של יום ראשון דראש השנה")),
 dict(sec="nach", ref="Rashi on II Chronicles 20:1:1", label='פירוש המיוחס לרש"י, דה"י ב כ:א', paytan="הקליר",
      q=["זְכוֹר עָרִיץ בָּעַמּוֹנִים נֶחְבָּא, פָּרַץ כַּרְמֵי עֵין גֶּדִי כְּהוּבָא"], kind="line",
      lit=[("zachor", "זכור עריץ בעמונים נחבא", None)], said=("rishon", "בְּפָרָשַׁת זָכוֹר")),
 dict(sec="nach", ref="Rashi on II Chronicles 22:11:1", label='פירוש המיוחס לרש"י, דה"י ב כב:יא', paytan="הקליר",
      q=["נָפַץ חֲדַר הַמִּטּוֹת"], kind="line",
      lit=[("rh1_musaf", "נפץ חדר המטות", None)], said=("editor", "בזכרונות דיום ראשון דראש השנה")),
 dict(sec="nach", ref="Rashi on II Chronicles 35:22:1", label='פירוש המיוחס לרש"י, דה"י ב לה:כב', paytan="הקליר",
      q=["כָּל הֲמוֹנָיו לָלֶכֶת אֲרַם נַהֲרַיִם, לְמַעַן לֹא תַעֲבֹר חֶרֶב כָּל שֶׁהוּא בְּאֶפְרַיִם"], kind="line",
      lit=[("kinot11", "ארם נהרים למען לא תעבר חרב כל שהוא באפרים", "בנוסח הקינה: \"כִּלָּה הֲמוֹנַי לֶכֶת\"; המפרש: \"כל המוניו ללכת\".")],
      said=("editor", "קינות לתשעה באב")),
 # ---------------- Rashi on Shas
 dict(sec="shas", ref="Rashi on Yoma 67a:1:2", label='רש"י יומא סז.', paytan="רבי אלעזר קליר",
      q=["ובשלשים קנים הוא קצב הריס", "ארחץ בנקיון כפות ברוחב ע\"ה מיל חריצותיה"], kind="line",
      lit=[("shekalim", "ובשלשים קנים הוא קצב הריס", "השורה הראשונה נמצאת בסילוק לפרשת שקלים."),
           ("w_erchatz", "ברוחב שבעים וחמשה מיל חריצותיה", "השורה השניה בסלוק \"כי אקח מועד\" שבקדושתא ארחץ בנקיון כפות; רש\"י: \"ע\"ה מיל\".")],
      said=("other", "Shibbolei HaLeket 28:9", "\"ארחץ בנקיון כפות\" של יום טוב שני של סוכות")),
 dict(sec="shas", ref="Rashi on Beitzah 33a:9:2", label='רש"י ביצה לג.', paytan="אחד מגאוני לומברדיא",
      q=["כך שמעתי בפיוט יוצר שיסד אחד מגאוני לומברדיא\"ה"], kind="content", lit=[],
      said=("rishon", "פיוט יוצר")),
 dict(sec="shas", ref="Rashi on Bava Metzia 69b:8:2", label='רש"י ב"מ סט:', paytan="רבינו משולם",
      q=["חכמי מדות מפריזים"], kind="line", lit=[("w_afik", "חכמי מדות מפריזים", None)]),
 # ---------------- Tosafos, in order of Shas
 dict(sec="tosafos", ref="Tosafot on Berakhot 6a:20:1", label='תוס\' ברכות ו. ד"ה מי כעמך ישראל', paytan="הפייטן",
      q=["טוטפת כלילו גדלי"], kind="line", lit=[("w_oryesha", "טוטפת כלילו גדלי", None)], said=("rishon", "ביום א' דפסח")),
 dict(sec="tosafos", ref="Tosafot on Berakhot 11a:24:1", label='תוס\' ברכות יא. ד"ה אחת ארוכה', paytan="",
      q=["אור יום הנף"], kind="line", lit=[("w_leil2", "אור יום הנף", None)]),
 dict(sec="tosafos", ref="Tosafot on Berakhot 17b", sub=(1, 0), label='תוס\' ברכות יז: ד"ה והם נזונין בזרוע', paytan="",
      q=["והם בזרוע עדיך באו", "עדיך לא באו"], kind="line",
      lit=[("rh2_musaf", "כי הם בזרוע. עדיך לא באו", "תוס' מגיהים \"עדיך באו\"; במחזור שלפנינו עדיין \"עָדֶיךָ לֹא בָאוּ\". הפיוט \"אפחד במעשי\", זכרונות ליום ב'.")]),
 dict(sec="tosafos", ref="Tosafot on Shabbat 114b:5:1", label='תוס\' שבת קיד: ד"ה ואמאי ליתקע', paytan="הפייטן",
      q=["אחר גמר מיצוי אכול בדצוי ורצוי"], kind="line", lit=[]),
 dict(sec="tosafos", ref="Tosafot on Eruvin 19a:19:1", label='תוס\' עירובין יט. ד"ה והאיכא תפתה', paytan="הפייט",
      q=["יקדו בהבהבי עלק"], kind="line",
      lit=[("w_eintzur", "יקדו כהבהבי עלק", "בנוסח ויקיטקסט: \"יִקְּדוּ כְּהַבְהֲבֵי עֶלֶק\"; תוס': \"בהבהבי\".")], said=("rishon", "בזולת אין צור חלף")),
 dict(sec="tosafos", ref="Tosafot on Eruvin 21a:18:1", label='תוס\' עירובין כא. ד"ה אחד משלשת אלפים', paytan="רבי אליעזר הקליר",
      q=["אלפים וארבע מאות בעולם מאריכה", "והזרת מותחת עד שנים בסיט", "גיא וכל עפרה בצרדה הכילו"], kind="line",
      lit=[("shekalim", "אלפים וארבע מאות בעולם מאריכה", None), ("shekalim", "והזרת מותחת עד שנים בסיט", None), ("shekalim", "גיא וכל עפרה בצרדה הכילו", None)], said=("rishon", "בסלוק אז ראית וספרת")),
 dict(sec="tosafos", ref="Tosafot on Pesachim 109a:7:1", label='תוס\' פסחים קט. ד"ה רביעית של תורה', paytan="הפייט",
      q=["הכוס סובב אצבעים על אצבעים", "לריבוע כוס ישועות"], kind="line",
      lit=[("shekalim", "והכוס סובב אצבעים על אצבעים", None), ("shekalim", "לרבוע כוס ישועות", None)]),
 dict(sec="tosafos", ref="Tosafot on Pesachim 115a:1:2", label='תוס\' פסחים קטו. ד"ה והדר אכיל חסא', paytan="ה\"ר יוסף טוב עלם",
      q=["למה שאר ירקות באין תחלה לפטור חזרת מברכה ראויה לה"], kind="line",
      lit=[("hagadol", "ולמה שאר ירקות באין תחלה", None)], said=("rishon", "בסדרו")),
 dict(sec="tosafos", ref="Tosafot on Pesachim 115b:9:1", label='תוס\' פסחים קטו: ד"ה למה עוקרין את השלחן', paytan="ה\"ר יוסף",
      q=["מושך מהקערה שני תבשילין ומגביה קערה ולימא הא לחמא עניא"], kind="line",
      lit=[("hagadol", "מושך מהקערה שני תבשילי", None)], said=("rishon", "בסדרו")),
 dict(sec="tosafos", ref="Tosafot on Pesachim 116b:4:2", label='תוס\' פסחים קטז: ד"ה ונאמר לפניו שירה חדשה', paytan="הפייט",
      q=["שירות אלה לשון נקבה מיוסדים כי תשועתם כיולדה"], kind="line",
      lit=[("w_eepatros", "שירות אלה לשון שירה מיסדים", "בנוסח ויקיטקסט: \"לְשׁוֹן שִׁירָה מְיֻסָּדִים\"; תוס': \"לשון נקבה מיוסדים\".")],
      said=("other", "Seder Troyes 10:6", "בשביעי של פסח (סדר טרויש)")),
 dict(sec="tosafos", ref="Tosafot on Pesachim 117b:19:1", label='תוס\' פסחים קיז: ד"ה רביעי אומר עליו הלל הגדול', paytan="ה\"ר יוסף טוב עלם",
      q=["קימעא לשתות מים יכנס אם חולה הוא או איסטניס"], kind="line",
      lit=[("hagadol", "קמעא לשתות מים יכנס", None)], said=("rishon", "בסדרו")),
 dict(sec="tosafos", ref="Tosafot on Yoma 8a:11:1", label='תוס\' יומא ח. ד"ה דכולי עלמא', paytan="רבינו אליהו הזקן",
      q=["יתד על אזניך תכסה", "תסקלוהו ויאמר המלך תלוהו"], kind="line",
      lit=[("w_emet", "יתד על אזנך תכסה", "בנוסח ויקיטקסט: \"אָזְנְךָ\"; תוס': \"אזניך\"."), ("w_emet", "סקילה תסקלוהו", "בנוסח ויקיטקסט: \"דַּנְתֶּם וְנִתְחַיַּב סְקִילָה תִּסְקְלוּהוּ, וַיֹּאמֶר הַמֶּלֶךְ תְּלֵהוּ\"; תוס': \"תלוהו\".")],
      said=("rishon", "באזהרות שלו")),
 dict(sec="tosafos", ref="Tosafot on Yoma 20b:3:1", label='תוס\' יומא כ: ד"ה משום חולשא', paytan="הפייט",
      q=["הוקמו מחצות דשן לנערה כפייס דשן הבערה"], kind="line",
      lit=[("w_asocheach", "הוקמו מחצות", "בנוסח ויקיטקסט (מחזור נירנברג): \"הוּקְמוּ מֵחֲצוֹת אֵפֶר לְנַעֲרָה, הֵרִים בְּפַיִס דֶּשֶׁן הַבְּעֵרָה\"; תוס' כאן: \"דשן לנערה כפייס דשן הבערה\".")]),
 dict(sec="tosafos", ref="Tosafot on Sukkah 36b:6:1", label='תוס\' סוכה לו: ד"ה מקורזלות', paytan="הפייט",
      q=["אשישת שלוחתו בקטב תלה אשישות להניץ בתיחוח קירזולה"], kind="line",
      lit=[("w_ashishat", "אשישת שלוחתו בקטב תלה", "בנוסח ויקיטקסט: \"בְּתִחוֹחַ קִרְזְלָהּ\"; תוס': \"בתיחוח קירזולה\".")]),
 dict(sec="tosafos", ref="Tosafot on Sukkah 49a:1:1", label='תוס\' סוכה מט. ד"ה שכל מזבח', paytan="רבינו אליהו הזקן",
      q=["אבני מזבח תוך ובר כן נגוזו ועבר"], kind="line", lit=[("w_emet", "אבני מזבח תוך ובר", None)], said=("rishon", "באזהרת אמת יהגה חיכי")),
 dict(sec="tosafos", ref="Tosafot on Rosh Hashanah 3a:1:1", label='תוס\' ר"ה ג. ד"ה וישמע הכנעני', paytan="הפייט",
      q=["כסות ולשון שינה היות כמלך ערד"], kind="line",
      lit=[("zachor", "כסות ולשון שנה היות מלך ערד", None)], said=("rishon", "בפזמון של פרשת זכור")),
 dict(sec="tosafos", ref="Tosafot on Rosh Hashanah 8b", sub=(0, 0), label='תוס\' ר"ה ח: ד"ה שהחדש מתכסה בו', paytan="ר\"א הקלירי",
      q=["מוספי חדש עשתי עשרה"], kind="line", lit=[("w_vechayot", "מוספי חדש עשתי עשרה", None)], said=("rishon", "באופן דמוסף דר\"ה וחיות אשר הנה מרובעות")),
 dict(sec="tosafos", ref="Tosafot on Rosh Hashanah 11a", sub=(12, 0), label='תוס\' ר"ה יא. ד"ה אלא דקאי בחג', paytan="רבי מאיר שליח צבור",
      q=["ומצות אפה ויאכלו בלילי חג פסח"], kind="line",
      lit=[("w_leil", "מצות אפה ויאכלו", None)], said=("rishon", "במעריב של פסח")),
 dict(sec="tosafos", ref="Tosafot on Rosh Hashanah 27a:15:1", label='תוס\' ר"ה כז. ד"ה כמאן מצלינן', paytan="ר\"א הקליר",
      q=["ומה שיסד ר\"א הקליר בגשם דשמיני עצרת כר\"א דאמר בתשרי נברא העולם ובשל פסח יסד כר' יהושע"], kind="content",
      lit=[("w_geshem", "אף ברי אתת", "תוס' מביאים את דעת הפייט ולא שורה; השורה המכוונת לא אותרה. כאן תחילת הגשם."),
           ("w_tal", "בדעתו אביעה חידות", "וכן בטל של פסח, לפי תוס' כר' יהושע (ניסן). כאן תחילת הטל.")],
      said=("rishon", "בגשם דשמיני עצרת, ובשל פסח")),
 dict(sec="tosafos", ref="Tosafot on Megillah 25a:4:1", label='תוס\' מגילה כה. ד"ה מפני שעושה מדותיו', paytan="הקליר",
      q=["צדקו אותו ואת בנו לא תשחטו ביום אחד"], kind="line",
      lit=[("w_asirim", "צדקו אותו ואת בנו ביום אחד בל תשחטו", "בנוסח ויקיטקסט: \"בְּיוֹם אֶחָד בַּל תִּשְׁחָטוּ\"; תוס': \"לא תשחטו ביום אחד\".")],
      said=("rishon", "בקדושת' שאנו אומרים ביום ב' של פסח")),
 dict(sec="tosafos", ref="Tosafot on Moed Katan 27b:1:1", label='תוס\' מו"ק כז: ד"ה בכליכה', paytan="",
      q=["עמון ומואב הוציאו את הכרובים וכליכה היו בם מסובבים"], kind="line",
      lit=[("kinot24", "והוציאו הכרובים ובכלבה היו בם מסובבים", "בנוסח הקינה: \"טָס עַמּוֹנִי וּמוֹאָבִי וְהוֹצִיאוּ הַכְּרוּבִים וּבִכְלִבָה\"; תוס' גורסים \"וכליכה\" בשני כפי\"ן.")],
      said=("rishon", "בפיוט של חרבן בית המקדש בתשעה באב")),
 dict(sec="tosafos", ref="Tosafot on Chagigah 11a:12:4", label='תוס\' חגיגה יא. ד"ה ברום ג\' אמות', paytan="הפייט",
      q=["אדם בקום חיש בשלש אמות והרביעית (וחמישית) אויר מגולה"], kind="line",
      lit=[("esther", "איש איש בשלש אמות והרביעית אויר מגלה", "בטקסט שבספריא: \"איש איש בשלש אמות\". הסליחה פותחת \"אדם בקום עלינו\" וחתומה מנחם ברבי מכיר.")],
      said=("rishon", "בסליחה")),
 dict(sec="tosafos", ref="Tosafot on Chagigah 12a:3:1", label='תוס\' חגיגה יב. ד"ה מסוף העולם ועד סופו', paytan="ה\"ר בנימין",
      q=["זה הים שליש עולמו במאה וששים ושש ועוד"], kind="line",
      lit=[("shekalim", "זה הים הגדול בשליש יושב במאה וששים ושש ועוד", "התאמה חלקית: בסילוק לפרשת שקלים הנוסח \"זה הים הגדול בשליש יושב במאה וששים ושש ועוד\". התוספות מייחסים לה\"ר בנימין ביוצר שלו, וכאן הוא בסילוק המיוחס לקליר.")],
      said=("rishon", "ביוצר שלו")),
 dict(sec="tosafos", ref="Tosafot on Chagigah 13a:4:1", label='תוס\' חגיגה יג. ד"ה ורגלי החיות', paytan="הקליר",
      q=["וחיות אשר הנה מרובעות לכסא כף רגל חמש מאות וחמש עשרה"], kind="line",
      lit=[("w_vechayot", "וחיות אשר הנה מרבעות כסא", None), ("w_vechayot", "כף רגל חמש מאות וחמש עשרה", None)], said=("rishon", "בקדושתא")),
 dict(sec="tosafos", ref="Tosafot on Yevamot 16b:6:1", label='תוס\' יבמות טז: ד"ה פסוק זה שר העולם', paytan="הפייט",
      q=["השר המשרת נער נקרא הוא מטטרון הנכבד והנורא", "תוקף מטטרון שר הנהפך לאש מבשר"], kind="line",
      lit=[("w_eshnabei", "תקיף מטטרון שר הנהפך לאש מבשר", "השורה השניה נמצאת באופן \"אשנבי שחקים\"; השורה הראשונה (\"השר המשרת נער נקרא\") לא נמצאה.")]),
 dict(sec="tosafos", ref="Tosafot on Bava Batra 14a:13:1", label='תוס\' ב"ב יד. ד"ה שבהן עמודים עומדין', paytan="הפייט",
      q=["תבנית אות יוסף עמודיו עשה כסף"], kind="line",
      lit=[("w_oryesha", "תבנית אות יוסף", None)]),
 dict(sec="tosafos", ref="Tosafot on Bava Batra 145b:2:1", label='תוס\' ב"ב קמה: ד"ה ואין השביעית משמטתה', paytan="ר' אליהו הזקן",
      q=["זמן עשר כסף כי ילונו בחצי ימיו יעזבנו"], kind="line", lit=[("w_emet", "זמן עשר כסף כי ילונו", None)]),
 dict(sec="tosafos", ref="Tosafot on Avodah Zarah 17a:7:1", label='תוס\' ע"ז יז. ד"ה לעלוקה', paytan="הפייט",
      q=["יקדו בהבהבי עלק"], kind="line",
      lit=[("w_eintzur", "יקדו כהבהבי עלק", "בנוסח ויקיטקסט: \"יִקְּדוּ כְּהַבְהֲבֵי עֶלֶק\"; תוס': \"בהבהבי\".")], said=("rishon", "בזולת של חנוכה")),
 dict(sec="tosafos", ref="Tosafot on Avodah Zarah 35a:7:1", label='תוס\' ע"ז לה. ד"ה מאי שנא האי קרא', paytan="הקליר",
      q=["אין להרהר על מה נחקקה שכולם נתנו בנשיקה"], kind="line",
      lit=[("parah", "אין להרהר ולומר על מה נחקקה", "בנוסח הסידור נוספה המילה \"ולומר\".")],
      said=("rishon", "בפרשת פרה אדומה")),
 dict(sec="tosafos", ref="Tosafot on Avodah Zarah 74b:8:1", label='תוס\' ע"ז עד: ד"ה דרש רבא נעוה ארתחו', paytan="רבינו יוסף ט\"ע",
      q=["קדירות אין צריך לפלחא כו' וקערות מותרות כי שקיל מדורא עלייהו לאנחא"], kind="line",
      lit=[("hagadol", "קדרות אין צריך לפלחא", None)], said=("rishon", "בסדר ביעור חמץ בקרובץ שבת הגדול")),
 dict(sec="tosafos", ref="Tosafot on Makkot 3b:4:1", label='תוס\' מכות ג: ד"ה איכא דאמרי', paytan="אזהרות (הגהת ר\"ת)",
      q=["זמן עשר (כסף) כי ילונו ולא במשפט בחצי ימיו יעזבנו"], kind="line",
      lit=[("w_emet", "זמן עשר כסף כי ילונו", "בנוסח ויקיטקסט: \"זְמַן עֶשֶׂר כֶּסֶף כִּי יִלְוֶנּוּ, בַּחֲצִי יָמָיו יַעַזְבֶנּוּ\", בלי \"ולא במשפט\".")]),
 dict(sec="tosafos", ref="Tosafot on Zevachim 86b:6:1", label='תוס\' זבחים פו: ד"ה משום חולשא דכהן גדול', paytan="הפייט",
      q=["הוקמו מחצות אפרה לבערה בפייס דשן הבערה"], kind="line",
      lit=[("w_asocheach", "הוקמו מחצות", "בנוסח ויקיטקסט (מחזור נירנברג): \"הוּקְמוּ מֵחֲצוֹת אֵפֶר לְנַעֲרָה, הֵרִים בְּפַיִס דֶּשֶׁן הַבְּעֵרָה\".")]),
 dict(sec="tosafos", ref="Tosafot on Menachot 35b:5:1", label='תוס\' מנחות לה: ד"ה וכמה שיעורייהו', paytan="ר\"א קליר",
      q=["גיא וכל עפרה בצרדה הכילו"], kind="line",
      lit=[("shekalim", "גיא וכל עפרה בצרדה הכילו", None)], said=("rishon", "בסילוק של פרשת שקלים")),
 dict(sec="tosafos", ref="Tosafot on Menachot 41b:13:1", label='תוס\' מנחות מא: ד"ה בית שמאי אומרים ארבע', paytan="רבי שלמה ספרדי",
      q=["המשולשל יהא נפשל כדי אצבעות ארבע"], kind="line",
      lit=[("w_sheshmeot", "המשלשל יהי נפשל כדי אצבעות ארבע", None)]),
 dict(sec="tosafos", ref="Tosafot on Chullin 42a:5:2", label='תוס\' חולין מב. ד"ה דרוסת הנץ', paytan="הפייט",
      q=["תוחלת ישראל מדרס הגס ונץ אפרוחים קרוצים"], kind="line",
      lit=[("selichot_polin5", "מדרס גז ונץ אפרוחיה קרוצים", "בנוסח הסליחות: \"מִדְרַס גֵּז וְנֵץ אֶפְרוֹחֶיהָ קְרוּצִים\"; תוס': \"מדרס הגס ונץ אפרוחים\".")],
      said=("rishon", "בסליחות")),
 dict(sec="tosafos", ref="Tosafot on Chullin 60a:10:1", label='תוס\' חולין ס. ד"ה פסוק זה שר העולם', paytan="הפייט",
      q=["תקיף מטטרון שנהפך לאש מבשר", "שר המשרת נער נקרא הוא מטטרון הנכבד והנורא"], kind="line",
      lit=[("w_eshnabei", "תקיף מטטרון שר הנהפך לאש מבשר", "השורה הראשונה נמצאת באופן \"אשנבי שחקים\"; השורה השניה לא נמצאה.")]),
 dict(sec="tosafos", ref="Tosafot on Chullin 109b:12:1", label='תוס\' חולין קט: ד"ה נדה דם טוהר', paytan="ר' אליעזר הקליר",
      q=["מן הדם טחול הדם מטומאת נדה (אשה) טהרת בתולי אשה ומאשת איש יפת תואר לאיש"], kind="line",
      lit=[("parah", "ומן הדם טחול", None)], said=("rishon", "בסלוק של פרשת פרה")),
 dict(sec="tosafos", ref="Tosafot on Bekhorot 55b:3:1", label='תוס\' בכורות נה: ד"ה הוא פרת דמעיקרא', paytan="רבי אליעזר הקליר",
      q=["פרת תוקפו כנגד שני נהרות"], kind="line",
      lit=[("shekalim", "והפרת תקפו כנגד שני הנהרות", None)], said=("rishon", "בפרשת שקלים ... בסילוק")),
 dict(sec="tosafos", ref="Tosafot on Arakhin 2b:6:2", label='תוס\' ערכין ב: ד"ה היודע להתעטף', paytan="הר' יוסף ט\"ע",
      q=["ומצאתי בסילוק א' שעשה הר' יוסף ט\"ע שנותן ציצית א' מלפניו ואחד מלאחריו מימין וכן לשמאל"], kind="content", lit=[]),
 dict(sec="tosafos", ref="Tosafot on Niddah 30a:17:1", label='תוס\' נדה ל. ד"ה ושמע מינה טבילה בזמנה', paytan="רבינו אליהו הזקן",
      q=["רבינו אליהו הזקן שיסד באזהרות טבילה בזמנה על ד' גדילים"], kind="content",
      lit=[("w_emet", "טבילה בזמנה, ועל ארבע גדילים", None)], said=("rishon", "באזהרות")),
]
