/* ============================================================================
   TALMUD FLORA — Kilayim (Seder Zeraim). Verified plant data module.
   window.KILAYIM_FLORA
   ----------------------------------------------------------------------------
   SOURCING DISCIPLINE (every claim carries provenance):
     badge "direct"   : verbatim primary text, Sefaria link attached.
     badge "lexicon"  : identification / lexical datum by a NAMED authority
                        (Feliks, Amar, Löw; Gledhill/Stearn for Latin) — stated
                        as their view, not as fact.
     badge "descript" : editorial synthesis / plain description (our words).
   confidence (of the modern ID): settled | disputed | conjectural.
   Hebrew is VERBATIM from Sefaria (Mishnah: Torat Emet; Rambam: Vilna).
   All science is a springboard, never a halachic source.
   ---------------------------------------------------------------------------- */

window.KILAYIM_FLORA = {
  meta: {
    masechta: { he: "כִּלְאַיִם", translit: "Kilayim", en: "Kilayim" },
    seder: "Zeraim",
    note: "Every plant named anywhere in Mishnah Kilayim (chs. 1-9). Wild/domestic pairs are separate cards, cross-linked by footnote.",
  },

  /* Verbatim Mishnah texts, keyed by ref (Sefaria, Torat Emet). */
  mishnah: {
    "1:1": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.1",
      he: `הַחִטִּים וְהַזּוּנִין אֵינָן כִּלְאַיִם זֶה בָזֶה. הַשְּׂעֹרִים וְשִׁבֹּלֶת שׁוּעָל, הַכֻּסְּמִין וְהַשִּׁיפוֹן, הַפּוֹל וְהַסַּפִּיר, הַפֻּרְקְדָן וְהַטֹּפֵחַ, וּפוֹל הַלָּבָן וְהַשְּׁעוּעִים, אֵינָם כִּלְאַיִם זֶה בָזֶה:` },
    "1:2": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.2",
      he: `הַקִּשּׁוּת וְהַמְּלָפְפוֹן, אֵינָם כִּלְאַיִם זֶה בָזֶה. רַבִּי יְהוּדָה אוֹמֵר, כִּלְאָיִם. חֲזֶרֶת וַחֲזֶרֶת גַּלִּים, עֻלְשִׁין וְעֻלְשֵׁי שָׂדֶה, כְּרֵשִׁים וּכְרֵשֵׁי שָׂדֶה, כֻּסְבָּר וְכֻסְבַּר שָׂדֶה, חַרְדָּל וְחַרְדָּל מִצְרִי, וּדְלַעַת הַמִּצְרִי וְהָרְמוּצָה, וּפוֹל מִצְרִי וְהֶחָרוּב, אֵינָם כִּלְאַיִם זֶה בָזֶה:` },
    "Pesachim 39a:3": { sefaria: "https://www.sefaria.org/Pesachim.39a.3",
      he: `חֲזֶרֶת — חַסָּא. עוּלְשִׁין — הִינְדְּבִי.` },
    "Pesachim 39a:9-10": { sefaria: "https://www.sefaria.org/Pesachim.39a.9-10",
      he: `וְאָמַר רָבָא: מַאי חֲזֶרֶת — חַסָּא. מַאי חַסָּא — דְּחַס רַחֲמָנָא עִילָּוַון.` },
    "1:3": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.3",
      he: `הַלֶּפֶת וְהַנָּפוּץ, וְהַכְּרוּב וְהַתְּרוֹבְתוֹר, הַתְּרָדִים וְהַלְּעוּנִים, אֵינָם כִּלְאַיִם זֶה בָזֶה. הוֹסִיף רַבִּי עֲקִיבָא, הַשּׁוּם וְהַשּׁוּמָנִית, הַבָּצָל וְהַבְּצַלְצוּל, וְהַתֻּרְמוֹס וְהַפְּלַסְלוֹס, אֵינָן כִּלְאַיִם זֶה בָזֶה:` },
    "1:4": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.4",
      he: `וּבָאִילָן, הָאֲגָסִים וְהַקְּרֻסְתּוּמֵלִין, וְהַפְּרִישִׁים וְהָעֻזְרָדִים, אֵינָם כִּלְאַיִם זֶה בָזֶה. הַתַּפּוּחַ וְהַחַזְרָד, הַפַּרְסְקִים וְהַשְּׁקֵדִין, וְהַשִּׁזָּפִין וְהָרִימִין, אַף עַל פִּי שֶׁדּוֹמִין זֶה לָזֶה, כִּלְאַיִם זֶה בָזֶה:` },
    "1:5": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.5",
      he: `הַצְּנוֹן וְהַנָּפוּץ, הַחַרְדָּל וְהַלַּפְסָן, וּדְלַעַת יְוָנִית עִם הַמִּצְרִית וְהָרְמוּצָה, אַף עַל פִּי שֶׁדּוֹמִין זֶה לָזֶה, כִּלְאַיִם זֶה בָזֶה:` },
    "1:8": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.1.8",
      he: `אֵין נוֹטְעִין יְרָקוֹת בְּתוֹךְ סַדָּן שֶׁל שִׁקְמָה. אֵין מַרְכִּיבִין פֵּיגָם עַל גַּבֵּי קִדָּה לְבָנָה, מִפְּנֵי שֶׁהוּא יָרָק בְּאִילָן. אֵין נוֹטְעִין יִחוּר שֶׁל תְּאֵנָה לְתוֹךְ הַחֲצוּב, שֶׁיְּהֵא מְקֵרוֹ. אֵין תּוֹחֲבִין זְמוֹרָה שֶׁל גֶּפֶן לְתוֹךְ הָאֲבַטִּיחַ, שֶׁתְּהֵא זוֹרֶקֶת מֵימֶיהָ לְתוֹכוֹ, מִפְּנֵי שֶׁהוּא אִילָן בְּיָרָק. אֵין נוֹתְנִין זֶרַע דְּלַעַת לְתוֹךְ הַחַלָּמִית, שֶׁתְּהֵא מְשַׁמַּרְתּוֹ, מִפְּנֵי שֶׁהוּא יָרָק בְּיָרָק:` },
    "2:5": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.2.5",
      he: `הָיְתָה שָׂדֵהוּ זְרוּעָה קַנְבּוֹס אוֹ לוּף, לֹא יְהֵא זוֹרֵעַ וּבָא עַל גַּבֵּיהֶם, שֶׁאֵינָן עוֹשִׂין אֶלָּא לִשְׁלֹשָׁה שָׁנִים. תְּבוּאָה שֶׁעָלָה בָהּ סְפִיחֵי אִסְטִיס, וְכֵן מְקוֹם הַגְּרָנוֹת שֶׁעָלוּ בָהֶן מִינִין הַרְבֵּה, וְכֵן תִּלְתָּן שֶׁהֶעֱלָה מִינֵי צְמָחִים, אֵין מְחַיְּבִין אוֹתוֹ לְנַכֵּשׁ. אִם נִכֵּשׁ אוֹ כִסַּח, אוֹמְרִים לוֹ, עֲקֹר אֶת הַכֹּל חוּץ מִמִּין אֶחָד:` },
    "2:8": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.2.8",
      he: `אֵין סוֹמְכִין לִשְׂדֵה תְבוּאָה חַרְדָּל וְחָרִיעַ, אֲבָל סוֹמְכִין לִשְׂדֵה יְרָקוֹת חַרְדָּל וְחָרִיעַ. וְסוֹמֵךְ לְבוּר, וּלְנִיר, וּלְגָפָה, וּלְדֶרֶךְ, וּלְגָדֵר גָּבוֹהַּ עֲשָׂרָה טְפָחִים, וּלְחָרִיץ שֶׁהוּא עָמֹק עֲשָׂרָה וְרָחָב אַרְבָּעָה, וּלְאִילָן שֶׁהוּא מֵסֵךְ עַל הָאָרֶץ, וּלְסֶלַע גָּבוֹהַּ עֲשָׂרָה וְרָחָב אַרְבָּעָה:` },
    "3:2": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.3.2",
      he: `כָּל מִין זְרָעִים אֵין זוֹרְעִים בַּעֲרוּגָה, וְכָל מִין יְרָקוֹת זוֹרְעִין בַּעֲרוּגָה. חַרְדָּל וַאֲפוּנִים הַשּׁוּפִין, מִין זְרָעִים. אֲפוּנִים הַגַּמְלָנִים, מִין יָרָק. גְּבוּל שֶׁהָיָה גָבוֹהַּ טֶפַח וְנִתְמַעֵט, כָּשֵׁר, שֶׁהָיָה כָשֵׁר מִתְּחִלָּתוֹ. הַתֶּלֶם וְאַמַּת הַמַּיִם שֶׁהֵם עֲמֻקִּים טֶפַח, זוֹרְעִים לְתוֹכָן שְׁלֹשָׁה זֵרְעוֹנִין, אֶחָד מִכָּאן, וְאֶחָד מִכָּאן, וְאֶחָד בָּאֶמְצַע:` },
    "5:8": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.5.8",
      he: `הַמְקַיֵּם קוֹצִים בַּכֶּרֶם, רַבִּי אֱלִיעֶזֶר אוֹמֵר, קִדֵּשׁ. וַחֲכָמִים אוֹמְרִים, לֹא קִדֵּשׁ אֶלָּא דָבָר שֶׁכָּמוֹהוּ מְקַיְּמִין. הָאִירוּס וְהַקִּסּוֹם וְשׁוֹשַׁנַּת הַמֶּלֶךְ וְכָל מִינֵי זְרָעִים, אֵינָן כִּלְאַיִם בַּכָּרֶם. הַקַּנְבּוֹס, רַבִּי טַרְפוֹן אוֹמֵר, אֵינוֹ כִלְאָיִם, וַחֲכָמִים אוֹמְרִים, כִּלְאָיִם. וְהַקִּנְרָס, כִּלְאַיִם בַּכָּרֶם:` },
    "6:5": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.6.5",
      he: `אֵיזֶהוּ אִילַן סְרָק. כָּל שֶׁאֵינוֹ עוֹשֶׂה פֵרוֹת. רַבִּי מֵאִיר אוֹמֵר, הַכֹּל אִילַן סְרָק, חוּץ מִן הַזַּיִת וְהַתְּאֵנָה. רַבִּי יוֹסֵי אוֹמֵר, כָּל שֶׁאֵין כָּמוֹהוּ נוֹטְעִין שָׂדוֹת שְׁלֵמוֹת, הֲרֵי זֶה אִילַן סְרָק:` },
    "9:1": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.9.1",
      he: `אֵין אָסוּר מִשּׁוּם כִּלְאַיִם אֶלָּא צֶמֶר וּפִשְׁתִּים. וְאֵינוֹ מִטַּמֵּא בִנְגָעִים אֶלָּא צֶמֶר וּפִשְׁתִּים. אֵין הַכֹּהֲנִים לוֹבְשִׁין לְשַׁמֵּשׁ בְּבֵית הַמִּקְדָּשׁ אֶלָּא צֶמֶר וּפִשְׁתִּים. צֶמֶר גְּמַלִּים וְצֶמֶר רְחֵלִים שֶׁטְּרָפָן זֶה בָזֶה, אִם רֹב מִן הַגְּמַלִּים, מֻתָּר, וְאִם רֹב מִן הָרְחֵלִים, אָסוּר. מֶחֱצָה לְמֶחֱצָה, אָסוּר. וְכֵן הַפִּשְׁתָּן וְהַקַּנְבּוֹס שֶׁטְּרָפָן זֶה בָזֶה:` },
    "9:7": { sefaria: "https://www.sefaria.org/Mishnah_Kilayim.9.7",
      he: `הַבַּרְסִין וְהַבַּרְדְּסִין וְהַדַּלְמְטִקְיוֹן וּמִנְעֲלוֹת הַפִּנּוֹן, לֹא יִלְבַּשׁ בָּהֶן עַד שֶׁיִּבְדֹּק. רַבִּי יוֹסֵי אוֹמֵר, הַבָּאִים מֵחוֹף הַיָּם וּמִמְּדִינַת הַיָּם אֵינָן צְרִיכִין בְּדִיקָה, מִפְּנֵי שֶׁחֶזְקָתָן בַּקַּנְבּוֹס. וּמִנְעָל שֶׁל זֶרֶד אֵין בּוֹ מִשּׁוּם כִּלְאָיִם:` },
  },

  /* Verbatim Rambam Peirush HaMishnayot glosses (Vilna), keyed by plant id.
     url is the chapter-level ref on Sefaria. */
  rambam: {
    url_1_1: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.1",
    zunin:        `מין ממיני החטה וישתנה בארץ בתבניתו וטבעו וע"כ נקרא זונין מענין היציאה מדרך היושר כמו לבם הזונה (יחזקאל ו)`,
    shibolet_shual: `הוא השעורים המדברית`,
    kusmin:       `מין ממיני החטה והוא החטה המדברית`,
    shifon:       `מין ממיני החטים המדבריות וצורת שניהם שוה ר"ל צורת כוסמין ושיפון ומפני זה אינן כלאים זה בזה`,
    pol:          `ידוע`,
    sapir:        `נקרא בלשון ערב מא"ש`,
    purkedan:     `נקרא בלשון ערב גלבא"ן ובלע"ז וש"ש`,
    tofeach:      `גרגרים לבנים עגולים קשים להשתבר וטבעו קרוב לטבע השעורים וקראוהו הרופאים קרטומן וכבר פירשנוה באשר הקדמנו`,
    pol_lavan:    `ידוע`,
    sheuim:       `נקראת בלשון ערבי לובי"א`,
    url_1_2: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.2",
    kishut:       `הקשות. הם הקשואין הירוקין ונקראין אלפקון:`,
    melafefon:    `והמלפפון. הם קשואים לבנים ונקראים בלשון ערב פיא"ר:`,
    chazeret:     `חזרת וחזרת גלים. החסא הגנית והחסא ההררית:`,
    ulshin:       `עולשין ועולשי שדה. נקרא אל הנדבא הפרדסי והמדברי:`,
    kreishim:     `כרישין וכרישי שדה. הכרתי הגני והמדברי:`,
    kusbar:       `כסבר וכסבר שדה. גני ומדברי:`,
    chardal:      `חרדל וחרדל מצרי. חרדל המדינה והמצרי:`,
    delaat_mitzri:`דלעת המצרית. ידוע:`,
    remutza:      `הרמוצה. רמוצה הוא תואר לדלעת ר"ל דלעת רמוצה והוא מין ממיני הדלועין וטעמו מר ואין ראוי לאוכלו עד שיטמנהו באפר חם ושם האפר החם שיש בו שארית מן האש רמץ ועל כן נקראת זו הדלעת רמוצה: ומה שאמר בכאן החרוב אינם החרובין אבל הוא מין מן הפול המצרי ושמו חרוב וכן פירשה הגמרא ואין הלכה כר"י:`,
    url_1_3: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.3",
    lefes:        `ידוע`,
    nafutz:       `הוא הצנון שבארץ הצבי והוא דומה ללפת`,
    kruv:         `ידוע`,
    terovtor:     `הוא כרוב מדברי שקלחיו דקין וכן פירשוהו בגמ'`,
    teradim:      `נקראים בערבי סלק`,
    leunim:       `נקראין בערבי קטף ובלע"ז ארמול"ש`,
    shum:         `ידוע`,
    shumanit:     `שום מדברי וראשו גוף א' גס ואינם חלקים מחוברים כמו האחרים והרופאים מכניסין אותו בצרכי הרפואות`,
    batzal:       `ידוע`,
    betzaltzul:   `בצל המדבר ואולי בצלצול שם לבצל הקטן וכן פירשוהו אחד מן המפרשים`,
    turmos:       `הוא בלשון ערב כן ובלע"ז פיישו"ל`,
    plaslos:      `תורמוס מדברי ואין הלכה כרבי עקיבא`,
    url_1_4: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.4",
    agasim:       `נקראים בלשון ערב עגו"ץ וההמון קורין לה ברקו"ק ובלע"ז מורייג"ס או אנפרשיג"ס`,
    krustumelin:  `הם בלשון ערב כמתה"י וההמון יקראו להם אגע"ז ובלע"ז פירא"ש`,
    perishim:     `הם חבושין בלע"ז קודונ"ץ`,
    uzradim:      `נקראין עזרו"ד ובלע"ז שורב"ש`,
    chazrad:      `נקרא אל עזרן`,
    parskim:      `בערבי אלפוך ובלע"ז פירשג"ש`,
    shkedin:      `בערבי אללוז ובלע"ז אמינדל"ס והפרסקין כשהן קטנים בתחלת צאתם דומין לשקדים וכשיהיו נגמרין בסופן נקראין בערבי ענא"ב`,
    rimin:        `נקרא אלנבק וכבר פירשנו אותו [פ' ומשנה א' בדמאי] ואמרו בגמ' יש מהן שהלכו בהן אחר הפרי ויש מהן שהלכו אחר העלין ר"ל אם הם דומים לפרי או לעלים לא יחשבוהו כלאים`,
    url_1_5: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.5",
    lafsan:       `לפסן. צמח שטעמו כטעם הלפת ירום על פני הארץ כשיעור אמה והרופאים קורין אותו לפסין:`,
    url_1_8: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.1.8",
    shikma:       `וסדן של שקמה גוף אילן השקמה וכבר פירשנוהו [בריש] מס' דמאי:`,
    peigam:       `פיגם נקרא בלשון ישמעאל ערב סראב ובלע"ז רודע:`,
    kida_levana:  `קדה. מין האילנות ויש לו ריח טוב תרגום וקדה (שמו' ל) וקציעתא ואומר מור ואהלות קציעות כל בגדותיך (תהלים מה):`,
    chatzuv:      `וחצוב. צמח שיש לו שרשים יורדים בעומק הארץ במישור אינם נוטים לכאן ולכאן ובהם תיחם יהושע חלקי השבטים ועל כן נקרא חצוב:`,
    avatiach:     `אבטיח בלע"ז אלכטין:`,
    chalamit:     `וחלמית. מין מהירקות ולא נודע לנו פירושו וי"א שהוא העשב הנקרא קטמיה בלשון ערב ובלע"ז מליו"ן:`,
    url_2_5: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.2.5",
    luf:          `ולוף כבר פירשנוהו שהוא מין ממיני הבצלים ואיני יודע היאך אלו עושות לשלש שנים`,
    kanbos:       `קנבוס. יש אומרים שהוא הנקרא בלשון ערב כרויא:`,
    istis:        `ופי' אסטיס הוא הניליגה והוא אינדו בלע"ז שצובעין בו תכלת:`,
    tiltan:       `ותלתן נקרא בערבי חלבא ובלע"ז פנגריג:`,
    url_2_8: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.2.8",
    charia:       `חריע בלשון ישמעאל עצפור:`,
    url_3_2: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.3.2",
    afunim_shufin:   `אפונים השופים הם הזרעים החלקים ממלת התרגום ושפית יתיה בשיפינא:`,
    afunim_gamlanim: `והאפונים הגמלנים הם הגסים וכן בלשון ארמית אומר לכל דבר גדול גמלאה איזה דבר שיהיה:`,
    url_5_8: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.5.8",
    irus:         `וארוס עשב שקורים בלשון ערב סוסנב"ר ונענ"ע רחב העלין ובלע"ז מינט"א:`,
    kissom:       `וקיסום בערבי ללבב ובלע"ז קוריול"ה:`,
    shoshanat_hamelech: `ושושנת המלך נקרא שקאיק אל נעמן ובלע"ז רושילא.`,
    kinras:       `והקינרס אל קנידיאה:`,
    url_9_1: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.9.1",
    pishtan:      `שש הוא פשתן... ואל יטעה אותך מה שהוא אומר במקומות מן התורה כתנת בד ומכנסי בד שהבד שם הפשתן כמו כן:`,
    url_9_7: "https://www.sefaria.org/Rambam_on_Mishnah_Kilayim.9.7",
    zered:        `ומנעל של זרד הוא דמות מנעל שנותנים תחת כף הרגל להלוך בה על היצועים והכסתות:`,
  },

  /* ---- PLANTS ---- (tranche 1: grains & legumes of Kilayim 1:1) */
  plants: [
    {
      id: "chitim", chapter: 1, mishnah_ref: "1:1",
      names: { he: "חִטִּים", translit: "chittim", en: ["wheat", "bread wheat"] },
      pair: { id: "zunin", he: "זוּנִין", note: "Paired in 1:1 as not-kilayim: wheat and its field-weed mimic." },
      identification: { binomial: "Triticum aestivum", family: "Poaceae", confidence: "settled",
        id_source: "Feliks; Amar; universal (Rambam: wheat). Ancient EY wheat was largely durum/emmer-derived hard wheat; the genus is undisputed.", badge: "lexicon" },
      etymology_latin: {
        Triticum: "Latin, name for wheat, from 'tritum' (threshed), via 'terere' (to rub/thresh).",
        aestivum: "Latin 'of summer', from 'aestas', a summer-ripening crop.",
      },
      kilayim: [{ with: "zunin", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: null, // Rambam gives no gloss on chitim
    },
    {
      id: "zunin", chapter: 1, mishnah_ref: "1:1",
      names: { he: "זוּנִין", translit: "zunin", en: ["darnel", "poison ryegrass", "tares"] },
      pair: { id: "chitim", he: "חִטִּים", note: "The weed that mimics wheat in the field; the Mishnah rules them not-kilayim." },
      identification: { binomial: "Lolium temulentum", family: "Poaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam = darnel.", badge: "lexicon" },
      etymology_latin: {
        Lolium: "Classical Latin name for darnel/ryegrass (Virgil, Pliny), a weedy grass of grainfields.",
        temulentum: "Latin 'drunken, intoxicated', for the stupor caused by its fungus-infected grain.",
      },
      kilayim: [{ with: "chitim", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "zunin",
      note_ambiguous: "A weedy grass, not a crop; included as it is treated as a grain-field species.",
    },
    {
      id: "seorim", chapter: 1, mishnah_ref: "1:1",
      names: { he: "שְׂעֹרִים", translit: "se'orim", en: ["barley"] },
      pair: { id: "shibolet-shual", he: "שִׁבֹּלֶת שׁוּעָל", note: "Paired not-kilayim in 1:1." },
      identification: { binomial: "Hordeum vulgare", family: "Poaceae", confidence: "settled",
        id_source: "Feliks; Amar; universal (Rambam: barley).", badge: "lexicon" },
      etymology_latin: {
        Hordeum: "Classical Latin for barley, probably from 'horrere' (to bristle), for the bristly awns.",
        vulgare: "Latin 'common, ordinary'.",
      },
      kilayim: [{ with: "shibolet-shual", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: null,
    },
    {
      id: "shibolet-shual", chapter: 1, mishnah_ref: "1:1",
      names: { he: "שִׁבֹּלֶת שׁוּעָל", translit: "shibolet shu'al", en: ["wild oat", "oat"] },
      pair: { id: "seorim", he: "שְׂעֹרִים", note: "Rambam: 'the wild barley'; paired not-kilayim with barley." },
      identification: { binomial: "Avena sterilis", family: "Poaceae", confidence: "disputed",
        id_source: "Rambam/tradition = oats (Avena); Rashi 'avena'. Amar leans Avena sterilis (native EY wild oat). Feliks dissents, arguing oats were uncultivated in Mishnaic EY.", badge: "lexicon" },
      etymology_latin: {
        Avena: "Classical Latin name for oats (and the oat-straw pipe), deeper origin uncertain.",
        sterilis: "Latin 'barren, unproductive' — the wild oat is worthless as a grain crop.",
      },
      kilayim: [{ with: "seorim", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "shibolet_shual",
    },
    {
      id: "kusmin", chapter: 1, mishnah_ref: "1:1",
      names: { he: "כֻּסְּמִין", translit: "kussemin", en: ["emmer", "spelt (trad.)"] },
      pair: { id: "shifon", he: "שִׁיפוֹן", note: "Paired not-kilayim in 1:1; Rambam: both are 'wild wheat' of the same form." },
      identification: { binomial: "Triticum dicoccum", family: "Poaceae", confidence: "disputed",
        id_source: "Feliks & Amar = emmer (the hulled wheat actually grown in ancient EY). Rambam/tradition & modern 'kusemet' = spelt (Triticum spelta), which Feliks shows was absent from ancient EY.", badge: "lexicon" },
      etymology_latin: {
        Triticum: "Latin for wheat, from 'tritum' (threshed).",
        dicoccum: "Greek 'di-' (two) + 'kokkos' (grain), 'two-grained', for the paired grains per spikelet.",
      },
      kilayim: [{ with: "shifon", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "kusmin",
    },
    {
      id: "shifon", chapter: 1, mishnah_ref: "1:1",
      names: { he: "שִׁיפוֹן", translit: "shifon", en: ["rye"] },
      pair: { id: "kusmin", he: "כֻּסְּמִין", note: "Paired not-kilayim with kusmin; Rambam pairs them by form." },
      identification: { binomial: "Secale cereale", family: "Poaceae", confidence: "disputed",
        id_source: "Modern Hebrew shifon = rye (leading ID); rye was scarce in Mishnaic EY, so Feliks proposed two-rowed barley, and some read Rambam's 'wild wheat' as einkorn (Triticum monococcum).", badge: "lexicon" },
      etymology_latin: {
        Secale: "Classical Latin name for a cereal (rye-like), used by Pliny.",
        cereale: "Latin 'of Ceres / of grain', from Ceres, goddess of agriculture.",
      },
      kilayim: [{ with: "kusmin", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "shifon",
    },
    {
      id: "pol", chapter: 1, mishnah_ref: "1:1",
      names: { he: "פּוֹל", translit: "pol", en: ["broad bean", "fava bean"] },
      pair: { id: "sapir", he: "סַפִּיר", note: "Paired not-kilayim in 1:1." },
      identification: { binomial: "Vicia faba", family: "Fabaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; universal (Rambam: broad bean). Biblical 'pol'.", badge: "lexicon" },
      etymology_latin: {
        Vicia: "Classical Latin for vetch, perhaps from 'vincire' (to bind), for the tendrils.",
        faba: "Classical Latin name for the broad bean.",
      },
      kilayim: [{ with: "sapir", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "pol",
    },
    {
      id: "sapir", chapter: 1, mishnah_ref: "1:1",
      names: { he: "סַפִּיר", translit: "sappir", en: ["Narbonne vetch"] },
      pair: { id: "pol", he: "פּוֹל", note: "Its plant and seed resemble the broad bean, hence the not-kilayim pairing." },
      identification: { binomial: "Vicia narbonensis", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks = French/Narbonne vetch (closely resembles pol). Rambam Arabic 'mash' points instead to mung bean, Vigna radiata.", badge: "lexicon" },
      etymology_latin: {
        Vicia: "Latin for vetch, perhaps from 'vincire' (to bind).",
        narbonensis: "'of Narbonne' (Narbo, southern France), the type locality.",
      },
      kilayim: [{ with: "pol", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "sapir",
    },
    {
      id: "purkedan", chapter: 1, mishnah_ref: "1:1",
      names: { he: "פֻּרְקְדָן", translit: "purkedan", en: ["red vetchling", "chickling vetch"] },
      pair: { id: "tofeach", he: "טֹפֵחַ", note: "Paired not-kilayim; Feliks pairs purkedan (L. cicera) with tofeach (L. sativus)." },
      identification: { binomial: "Lathyrus cicera", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks = Lathyrus cicera. Rambam Arabic 'julban' = the chickling-vetch group (often mapped to L. sativus). Genus Lathyrus agreed; species disputed.", badge: "lexicon" },
      etymology_latin: {
        Lathyrus: "Greek 'lathyros', an ancient name for a pulse (pea/vetchling).",
        cicera: "Latin 'cicera/cicercula', old name for the chickling/grass pea, related to 'cicer' (chickpea).",
      },
      kilayim: [{ with: "tofeach", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "purkedan",
    },
    {
      id: "tofeach", chapter: 1, mishnah_ref: "1:1",
      names: { he: "טֹפֵחַ", translit: "tofeach", en: ["grass pea", "chickling pea"] },
      pair: { id: "purkedan", he: "פֻּרְקְדָן", note: "Paired not-kilayim with purkedan." },
      identification: { binomial: "Lathyrus sativus", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks & Amar = grass pea (L. sativus). Rambam's laaz 'kartuman' is the Arabic for safflower (see charia) — a divergent gloss, which is why the Lathyrus reading leads.", badge: "lexicon" },
      etymology_latin: {
        Lathyrus: "Greek 'lathyros', ancient name for a leguminous pulse.",
        sativus: "Latin 'sown, cultivated', from 'serere' (to sow).",
      },
      kilayim: [{ with: "purkedan", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "tofeach",
    },
    {
      id: "pol-lavan", chapter: 1, mishnah_ref: "1:1",
      names: { he: "פּוֹל הַלָּבָן", translit: "pol ha-lavan", en: ["hyacinth bean", "lablab bean"] },
      pair: { id: "sheuim", he: "שְׁעוּעִים", note: "Paired not-kilayim in 1:1." },
      identification: { binomial: "Lablab purpureus", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks = hyacinth bean (Lablab purpureus, syn. Dolichos lablab). Modern 'white bean' = Phaseolus vulgaris is an American import unknown to the Mishnah, so the ancient referent is an Old-World bean.", badge: "lexicon" },
      etymology_latin: {
        Lablab: "From the Arabic vernacular 'lablāb', a twining bean, adopted by Linnaeus.",
        purpureus: "Latin 'purple', for the purplish flowers, pods and stems.",
      },
      kilayim: [{ with: "sheuim", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "pol_lavan",
    },
    {
      id: "sheuim", chapter: 1, mishnah_ref: "1:1",
      names: { he: "שְׁעוּעִים", translit: "she'u'im", en: ["cowpea", "black-eyed pea"] },
      pair: { id: "pol-lavan", he: "פּוֹל הַלָּבָן", note: "Paired not-kilayim with pol ha-lavan." },
      identification: { binomial: "Vigna unguiculata", family: "Fabaceae", confidence: "settled",
        id_source: "Feliks (she'uit = Nile cowpea, now within V. unguiculata); Rambam Arabic 'lubya' = cowpea — both converge. Modern 'she'uit' = Phaseolus is anachronistic (American genus).", badge: "lexicon" },
      etymology_latin: {
        Vigna: "Named for Domenico Vigna (d. 1647), Italian botanist, prefect of the Pisa botanic garden.",
        unguiculata: "Latin 'with a small claw' (diminutive of 'unguis', claw), for the small clawed petal bases.",
      },
      kilayim: [{ with: "pol-lavan", ruling: "not_kilayim", ref: "Kilayim 1:1" }],
      rambam: "sheuim",
    },

    /* ---- tranche 2: vegetables, herbs, gourds & legumes of Kilayim 1:2 ---- */
    {
      id: "kishut", chapter: 1, mishnah_ref: "1:2",
      names: { he: "קִשּׁוּת", translit: "kishut", en: ["snake cucumber", "Armenian cucumber"] },
      pair: { id: "melafefon", he: "מְלָפְפוֹן", note: "Same species as melafefon, a different variety; 1:2 pairs them." },
      identification: { binomial: "Cucumis melo var. flexuosus", family: "Cucurbitaceae", confidence: "settled",
        id_source: "Feliks = snake cucumber; Rambam Arabic al-faqqus (the green cucumbers).", badge: "lexicon" },
      etymology_latin: {
        Cucumis: "Latin, the classical name for the cucumber.",
        melo: "Latin, short for 'melopepo', from Greek 'mēlopepōn' (apple-melon).",
        flexuosus: "Latin 'winding, tortuous', for the long curved fruit.",
      },
      kilayim: [{ with: "melafefon", ruling: "not_kilayim", ref: "Kilayim 1:2", note: "Tana kama: not kilayim; R' Yehuda: kilayim. Rambam rules not like R' Yehuda." }],
      rambam: "kishut",
    },
    {
      id: "melafefon", chapter: 1, mishnah_ref: "1:2",
      names: { he: "מְלָפְפוֹן", translit: "melafefon", en: ["muskmelon", "melon"] },
      pair: { id: "kishut", he: "קִשּׁוּת", note: "Same species (Cucumis melo), different variety." },
      identification: { binomial: "Cucumis melo", family: "Cucurbitaceae", confidence: "settled",
        id_source: "Feliks = muskmelon (same species as kishut). Rambam Arabic פיא\"ר (white cucumbers), vocalization uncertain.", badge: "lexicon" },
      etymology_latin: {
        Cucumis: "Latin, classical name for the cucumber.",
        melo: "Latin, short for 'melopepo', Greek 'mēlopepōn' (apple-melon).",
      },
      kilayim: [{ with: "kishut", ruling: "not_kilayim", ref: "Kilayim 1:2", note: "R' Yehuda dissents (kilayim)." }],
      rambam: "melafefon",
      note_ambiguous: "Greek loanword (melopepon); the name carries no weight against the identification.",
    },
    {
      id: "chazeret", chapter: 1, mishnah_ref: "1:2",
      names: { he: "חֲזֶרֶת", translit: "chazeret", en: ["lettuce", "garden lettuce"] },
      pair: { id: "chazeret-galim", he: "חֲזֶרֶת גַּלִּים", note: "Cultivated lettuce; its wild counterpart is chazeret galim." },
      identification: { binomial: "Lactuca sativa", family: "Asteraceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Bavli Pesachim 39a equates chazeret with Aramaic חסא; Rambam Arabic al-khass.", badge: "lexicon" },
      etymology_latin: {
        Lactuca: "Latin, from 'lac' (milk), for the milky latex.",
        sativa: "Latin 'sown, cultivated', from 'serere' (to sow).",
      },
      kilayim: [{ with: "chazeret-galim", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "chazeret",
      extra_sources: ["Pesachim 39a:3", "Pesachim 39a:9-10"],
      note_halacha: "First of the maror species (Pesachim 2:6).",
    },
    {
      id: "chazeret-galim", chapter: 1, mishnah_ref: "1:2",
      names: { he: "חֲזֶרֶת גַּלִּים", translit: "chazeret gallim", en: ["wild lettuce"] },
      pair: { id: "chazeret", he: "חֲזֶרֶת", note: "The wild/feral counterpart of cultivated lettuce; Rambam: 'the mountain lettuce'." },
      identification: { binomial: "Lactuca serriola", family: "Asteraceae", confidence: "disputed",
        id_source: "Feliks: the wild lettuce, same min gone feral (Lactuca serriola, the wild ancestor of L. sativa).", badge: "lexicon" },
      etymology_latin: {
        Lactuca: "Latin, from 'lac' (milk), for the milky sap.",
        serriola: "Latin, a diminutive linked to 'serra' (saw), for the prickly saw-toothed leaf edges.",
      },
      kilayim: [{ with: "chazeret", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "chazeret",
    },
    {
      id: "ulshin", chapter: 1, mishnah_ref: "1:2",
      names: { he: "עֻלְשִׁין", translit: "ulshin", en: ["endive", "chicory"] },
      pair: { id: "ulshei-sadeh", he: "עֻלְשֵׁי שָׂדֶה", note: "Cultivated endive; wild counterpart is ulshei sadeh." },
      identification: { binomial: "Cichorium endivia", family: "Asteraceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Rambam Arabic al-hindiba (the garden and desert kinds). Pesachim 39a: הינדבי.", badge: "lexicon" },
      etymology_latin: {
        Cichorium: "Latin, from Greek 'kichorion', the classical name for chicory/endive.",
        endivia: "Medieval Latin (via Arabic hindiba); ultimate origin uncertain, possibly Egyptian.",
      },
      kilayim: [{ with: "ulshei-sadeh", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "ulshin",
    },
    {
      id: "ulshei-sadeh", chapter: 1, mishnah_ref: "1:2",
      names: { he: "עֻלְשֵׁי שָׂדֶה", translit: "ulshei sadeh", en: ["wild chicory"] },
      pair: { id: "ulshin", he: "עֻלְשִׁין", note: "The wild/field counterpart of endive; Rambam: 'the desert hindiba'." },
      identification: { binomial: "Cichorium intybus", family: "Asteraceae", confidence: "settled",
        id_source: "Feliks; Amar: wild chicory (C. intybus), the field form of the endive min.", badge: "lexicon" },
      etymology_latin: {
        Cichorium: "Latin from Greek 'kichorion', chicory.",
        intybus: "Latin/Greek classical name for wild chicory/endive.",
      },
      kilayim: [{ with: "ulshin", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "ulshin",
    },
    {
      id: "kreishim", chapter: 1, mishnah_ref: "1:2",
      names: { he: "כְּרֵשִׁים", translit: "kereshim", en: ["leek", "kurrat"] },
      pair: { id: "kreishei-sadeh", he: "כְּרֵשֵׁי שָׂדֶה", note: "Cultivated leek; wild counterpart is kreishei sadeh." },
      identification: { binomial: "Allium ampeloprasum", family: "Amaryllidaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Rambam Arabic al-kurrat (garden and desert). Family Amaryllidaceae (APG; formerly Alliaceae).", badge: "lexicon" },
      etymology_latin: {
        Allium: "Classical Latin for garlic.",
        ampeloprasum: "Greek 'ampelos' (vine) + 'prason' (leek), 'vine-leek'.",
      },
      kilayim: [{ with: "kreishei-sadeh", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "kreishim",
    },
    {
      id: "kreishei-sadeh", chapter: 1, mishnah_ref: "1:2",
      names: { he: "כְּרֵשֵׁי שָׂדֶה", translit: "kereshei sadeh", en: ["wild leek"] },
      pair: { id: "kreishim", he: "כְּרֵשִׁים", note: "The wild/field counterpart of the leek." },
      identification: { binomial: "Allium ampeloprasum", family: "Amaryllidaceae", confidence: "disputed",
        id_source: "Feliks; Amar: the wild leek, same min as kreishim (wild A. ampeloprasum).", badge: "lexicon" },
      etymology_latin: {
        Allium: "Classical Latin for garlic.",
        ampeloprasum: "Greek 'vine-leek' (ampelos + prason).",
      },
      kilayim: [{ with: "kreishim", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "kreishim",
    },
    {
      id: "kusbar", chapter: 1, mishnah_ref: "1:2",
      names: { he: "כֻּסְבָּר", translit: "kusbar", en: ["coriander", "cilantro"] },
      pair: { id: "kusbar-sadeh", he: "כֻּסְבַּר שָׂדֶה", note: "Cultivated coriander; wild counterpart is kusbar sadeh." },
      identification: { binomial: "Coriandrum sativum", family: "Apiaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Rambam Arabic kuzbara (garden and desert).", badge: "lexicon" },
      etymology_latin: {
        Coriandrum: "Latin from Greek 'koriannon'; traditionally linked to 'koris' (bug), for the smell of the unripe fruit (debated).",
        sativum: "Latin 'sown, cultivated'.",
      },
      kilayim: [{ with: "kusbar-sadeh", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "kusbar",
    },
    {
      id: "kusbar-sadeh", chapter: 1, mishnah_ref: "1:2",
      names: { he: "כֻּסְבַּר שָׂדֶה", translit: "kusbar sadeh", en: ["wild coriander"] },
      pair: { id: "kusbar", he: "כֻּסְבָּר", note: "The wild/field counterpart of coriander (Rambam: 'desert')." },
      identification: { binomial: "Coriandrum sativum", family: "Apiaceae", confidence: "conjectural",
        id_source: "Feliks: the wild/field form of coriander, same min; the exact wild taxon (a field umbellifer) is not fixed.", badge: "lexicon" },
      etymology_latin: {
        Coriandrum: "Latin from Greek 'koriannon'.",
        sativum: "Latin 'cultivated'.",
      },
      kilayim: [{ with: "kusbar", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "kusbar",
    },
    {
      id: "chardal", chapter: 1, mishnah_ref: "1:2",
      names: { he: "חַרְדָּל", translit: "chardal", en: ["black mustard"] },
      pair: { id: "chardal-mitzri", he: "חַרְדָּל מִצְרִי", note: "Not kilayim with Egyptian mustard (1:2), yet IS kilayim with charlock/lafsan (1:5) — halacha tracks resemblance, not genus." },
      identification: { binomial: "Brassica nigra", family: "Brassicaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Rambam Arabic khardal.", badge: "lexicon" },
      etymology_latin: {
        Brassica: "Classical Latin for cabbage.",
        nigra: "Latin 'black', for the dark seeds.",
      },
      kilayim: [
        { with: "chardal-mitzri", ruling: "not_kilayim", ref: "Kilayim 1:2" },
        { with: "lafsan", ruling: "kilayim", ref: "Kilayim 1:5", note: "Both partners (chardal-mitzri, lafsan) are genus Sinapis, opposite rulings." },
      ],
      rambam: "chardal",
    },
    {
      id: "chardal-mitzri", chapter: 1, mishnah_ref: "1:2",
      names: { he: "חַרְדָּל מִצְרִי", translit: "chardal mitzri", en: ["white mustard", "Egyptian mustard"] },
      pair: { id: "chardal", he: "חַרְדָּל", note: "Different genus from plain chardal (Sinapis vs Brassica), yet not kilayim with it." },
      identification: { binomial: "Sinapis alba", family: "Brassicaceae", confidence: "disputed",
        id_source: "Löw & tradition: white mustard (Sinapis alba), a different genus from plain chardal. Some read a Brassica cultivar; species not fully settled.", badge: "lexicon" },
      etymology_latin: {
        Sinapis: "Latin 'sinapis', mustard, from Greek 'sinapi' (of pre-Greek/Egyptian origin).",
        alba: "Latin 'white', for the pale seeds and flowers.",
      },
      kilayim: [{ with: "chardal", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "chardal",
    },
    {
      id: "delaat-hamitzri", chapter: 1, mishnah_ref: "1:2",
      names: { he: "דְּלַעַת הַמִּצְרִי", translit: "dela'at ha-mitzri", en: ["Egyptian gourd"] },
      pair: { id: "remutza", he: "רְמוּצָה", note: "Paired not-kilayim with the remutzah gourd in 1:2." },
      identification: { binomial: "Cucurbitaceae", family: "Cucurbitaceae", confidence: "conjectural",
        id_source: "Distinguished in 1:5 from the 'Grecian gourd' (Lagenaria); the Egyptian gourd's precise species is unsettled (a Cucurbit variety). Rambam: 'known'.", badge: "lexicon" },
      etymology_latin: { Cucurbitaceae: "Latin 'cucurbita' (gourd), the family name." },
      kilayim: [{ with: "remutza", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "delaat_mitzri",
    },
    {
      id: "remutza", chapter: 1, mishnah_ref: "1:2",
      names: { he: "רְמוּצָה", translit: "remutzah", en: ["remutzah gourd"] },
      pair: { id: "delaat-hamitzri", he: "דְּלַעַת הַמִּצְרִי", note: "A bitter gourd variety." },
      identification: { binomial: "Cucurbitaceae", family: "Cucurbitaceae", confidence: "conjectural",
        id_source: "Rambam: a bitter gourd (min of gourds) roasted in hot embers (רמץ) to be edible — 'remutzah' is a descriptor of the gourd, not a distinct species.", badge: "descript" },
      etymology_latin: { Cucurbitaceae: "Latin 'cucurbita' (gourd)." },
      kilayim: [{ with: "delaat-hamitzri", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "remutza",
      note_ambiguous: "A descriptor (roasted-in-embers gourd), not a fixed species.",
    },
    {
      id: "pol-mitzri", chapter: 1, mishnah_ref: "1:2",
      names: { he: "פּוֹל מִצְרִי", translit: "pol mitzri", en: ["cowpea", "Egyptian bean"] },
      pair: { id: "charuv", he: "חָרוּב", note: "Paired not-kilayim with the long-podded 'charuv' cowpea." },
      identification: { binomial: "Vigna unguiculata", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks & most: cowpea (Vigna unguiculata). A minority reads 'Egyptian bean' as Colocasia (taro) or Lablab.", badge: "lexicon" },
      etymology_latin: {
        Vigna: "For Domenico Vigna (d. 1647), Italian botanist.",
        unguiculata: "Latin 'with a small claw', for the clawed petal bases.",
      },
      kilayim: [{ with: "charuv", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "remutza",
    },
    {
      id: "charuv", chapter: 1, mishnah_ref: "1:2",
      names: { he: "חָרוּב", translit: "charuv", en: ["yard-long bean", "asparagus bean"] },
      pair: { id: "pol-mitzri", he: "פּוֹל מִצְרִי", note: "A long-podded form of the cowpea group — NOT the carob tree (Rambam explicit)." },
      identification: { binomial: "Vigna unguiculata subsp. sesquipedalis", family: "Fabaceae", confidence: "disputed",
        id_source: "Rambam (1:2): charuv here is a type of pol mitzri named charuv, NOT Ceratonia siliqua (carob). Feliks: the yard-long/long-podded cowpea.", badge: "lexicon" },
      etymology_latin: {
        Vigna: "For Domenico Vigna, Italian botanist.",
        unguiculata: "Latin 'with a small claw'.",
        sesquipedalis: "Latin 'a foot and a half long' (sesqui- + pes/pedis), for the very long pods.",
      },
      kilayim: [{ with: "pol-mitzri", ruling: "not_kilayim", ref: "Kilayim 1:2" }],
      rambam: "remutza",
      note_ambiguous: "'Charuv' here is a legume (long-podded cowpea), not the carob tree.",
    },

    /* ---- tranche 3: vegetables & legumes of Kilayim 1:3 ---- */
    {
      id: "lefes", chapter: 1, mishnah_ref: "1:3",
      names: { he: "לֶפֶת", translit: "lefet", en: ["turnip"] },
      pair: { id: "nafutz", he: "נָפוּץ", note: "Not kilayim with nafutz (1:3), which is itself kilayim with the radish (1:5) — halacha by resemblance." },
      identification: { binomial: "Brassica rapa", family: "Brassicaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Rambam: 'known'.", badge: "lexicon" },
      etymology_latin: { Brassica: "Classical Latin for cabbage.", rapa: "Latin 'rapa/rapum', the ancient name for the turnip." },
      kilayim: [{ with: "nafutz", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "lefes",
    },
    {
      id: "nafutz", chapter: 1, mishnah_ref: "1:3",
      names: { he: "נָפוּץ", translit: "nafutz", en: ["wild radish", "white charlock"] },
      pair: { id: "lefes", he: "לֶפֶת", note: "Rambam: 'the radish of Eretz Tzvi, resembling the turnip'." },
      identification: { binomial: "Raphanus raphanistrum", family: "Brassicaceae", confidence: "disputed",
        id_source: "Feliks/Amar (following Rambam): a radish-type resembling the turnip; the exact wild taxon is unsettled.", badge: "lexicon" },
      etymology_latin: {
        Raphanus: "Latin from Greek 'rhaphanos', the radish; traditionally 'quick-appearing' (rha- + phainesthai).",
        raphanistrum: "Latin '-astrum' (wild/inferior resemblance), i.e. 'false/wild radish'.",
      },
      kilayim: [
        { with: "lefes", ruling: "not_kilayim", ref: "Kilayim 1:3" },
        { with: "tzenon", ruling: "kilayim", ref: "Kilayim 1:5", note: "Not kilayim with turnip, yet kilayim with radish — nafutz resembles both." },
      ],
      rambam: "nafutz",
    },
    {
      id: "kruv", chapter: 1, mishnah_ref: "1:3",
      names: { he: "כְּרוּב", translit: "keruv", en: ["cabbage", "kale"] },
      pair: { id: "terovtor", he: "תְּרוֹבְתוֹר", note: "Paired not-kilayim with terovtor." },
      identification: { binomial: "Brassica oleracea", family: "Brassicaceae", confidence: "settled",
        id_source: "Feliks; Amar; Rambam Arabic kurunb (cabbage/kale).", badge: "lexicon" },
      etymology_latin: { Brassica: "Classical Latin for cabbage.", oleracea: "Latin 'of the pot-herb/kitchen garden', from 'holus' (vegetable)." },
      kilayim: [{ with: "terovtor", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "kruv",
    },
    {
      id: "terovtor", chapter: 1, mishnah_ref: "1:3",
      names: { he: "תְּרוֹבְתוֹר", translit: "terovtor", en: ["cauliflower", "branching cabbage"] },
      pair: { id: "kruv", he: "כְּרוּב", note: "Rambam: 'wild cabbage, thin stalks'; same species as cabbage." },
      identification: { binomial: "Brassica oleracea", family: "Brassicaceae", confidence: "disputed",
        id_source: "Amar (per Rambam) = a cultivated form of B. oleracea (cauliflower/branching kale); species settled, variety not.", badge: "lexicon" },
      etymology_latin: { Brassica: "Classical Latin for cabbage.", oleracea: "Latin 'of the pot-herb', from 'holus'." },
      kilayim: [{ with: "kruv", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "terovtor",
    },
    {
      id: "teradim", chapter: 1, mishnah_ref: "1:3",
      names: { he: "תְּרָדִים", translit: "teradim", en: ["chard", "leaf beet"] },
      pair: { id: "leunim", he: "לְעוּנִים", note: "Different genus from orache, same family — yet not kilayim." },
      identification: { binomial: "Beta vulgaris", family: "Amaranthaceae", confidence: "settled",
        id_source: "Feliks; Amar; Rambam Arabic silq (chard/beet). Formerly Chenopodiaceae, now Amaranthaceae.", badge: "lexicon" },
      etymology_latin: { Beta: "Classical Latin name for the beet.", vulgaris: "Latin 'common, ordinary'." },
      kilayim: [{ with: "leunim", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "teradim",
    },
    {
      id: "leunim", chapter: 1, mishnah_ref: "1:3",
      names: { he: "לְעוּנִים", translit: "le'unim", en: ["orache", "saltbush"] },
      pair: { id: "teradim", he: "תְּרָדִים", note: "Different genus (Atriplex) from beet (Beta), same family Amaranthaceae — one min." },
      identification: { binomial: "Atriplex halimus", family: "Amaranthaceae", confidence: "disputed",
        id_source: "Feliks; Amar; Rambam Arabic al-qataf (orache). Genus Atriplex agreed; species (A. halimus vs annual oraches) open.", badge: "lexicon" },
      etymology_latin: { Atriplex: "Classical Latin (from Greek atraphaxis) for the orache.", halimus: "Greek 'halimos' (maritime), from 'hals' (salt), for the salt-tolerant habit." },
      kilayim: [{ with: "teradim", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "leunim",
    },
    {
      id: "shum", chapter: 1, mishnah_ref: "1:3",
      names: { he: "שׁוּם", translit: "shum", en: ["garlic"] },
      pair: { id: "shumanit", he: "שׁוּמָנִית", note: "Paired not-kilayim (R' Akiva's addition)." },
      identification: { binomial: "Allium sativum", family: "Amaryllidaceae", confidence: "settled",
        id_source: "Feliks; Amar; Rambam Arabic thum (garlic).", badge: "lexicon" },
      etymology_latin: { Allium: "Classical Latin for garlic.", sativum: "Latin 'cultivated, sown'." },
      kilayim: [{ with: "shumanit", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "shum",
    },
    {
      id: "shumanit", chapter: 1, mishnah_ref: "1:3",
      names: { he: "שׁוּמָנִית", translit: "shumanit", en: ["wild garlic"] },
      pair: { id: "shum", he: "שׁוּם", note: "Rambam: 'wild garlic' with a coarse single head; the wild counterpart of garlic." },
      identification: { binomial: "Allium ampeloprasum", family: "Amaryllidaceae", confidence: "disputed",
        id_source: "Klein/Jastrow: 'wild garlic' (diminutive of shum). Species unsettled; A. ampeloprasum most cited.", badge: "lexicon" },
      etymology_latin: { Allium: "Classical Latin for garlic.", ampeloprasum: "Greek 'vine-leek' (ampelos + prason)." },
      kilayim: [{ with: "shum", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "shumanit",
    },
    {
      id: "batzal", chapter: 1, mishnah_ref: "1:3",
      names: { he: "בָּצָל", translit: "batzal", en: ["onion"] },
      pair: { id: "betzaltzul", he: "בְּצַלְצוּל", note: "Paired not-kilayim with the small/wild onion." },
      identification: { binomial: "Allium cepa", family: "Amaryllidaceae", confidence: "settled",
        id_source: "Feliks; Amar; Rambam Arabic basal (onion).", badge: "lexicon" },
      etymology_latin: { Allium: "Classical Latin for garlic and its relatives.", cepa: "Classical Latin name for the onion." },
      kilayim: [{ with: "betzaltzul", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "batzal",
    },
    {
      id: "betzaltzul", chapter: 1, mishnah_ref: "1:3",
      names: { he: "בְּצַלְצוּל", translit: "betzaltzul", en: ["small onion", "wild onion"] },
      pair: { id: "batzal", he: "בָּצָל", note: "Rambam: 'desert onion'; a small/wild onion, the counterpart of batzal." },
      identification: { binomial: "Allium ampeloprasum", family: "Amaryllidaceae", confidence: "disputed",
        id_source: "Klein/Jastrow: small onion (diminutive of batzal). Species unsettled (pearl-onion form, or a wild Allium, or shallot).", badge: "lexicon" },
      etymology_latin: { Allium: "Classical Latin for garlic.", ampeloprasum: "Greek 'vine-leek'." },
      kilayim: [{ with: "batzal", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "betzaltzul",
    },
    {
      id: "turmos", chapter: 1, mishnah_ref: "1:3",
      names: { he: "תֻּרְמוֹס", translit: "turmos", en: ["white lupine"] },
      pair: { id: "plaslos", he: "פְּלַסְלוֹס", note: "Paired not-kilayim with the wild lupine (R' Akiva)." },
      identification: { binomial: "Lupinus albus", family: "Fabaceae", confidence: "settled",
        id_source: "Feliks; Rambam = lupine. Greek loan 'thermos' underlies the name; Lupinus termis = L. albus.", badge: "lexicon" },
      etymology_latin: { Lupinus: "Latin 'of the wolf' (lupus), reputed to exhaust the soil.", albus: "Latin 'white'." },
      kilayim: [{ with: "plaslos", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "turmos",
    },
    {
      id: "plaslos", chapter: 1, mishnah_ref: "1:3",
      names: { he: "פְּלַסְלוֹס", translit: "pelaslos", en: ["yellow/wild lupine"] },
      pair: { id: "turmos", he: "תֻּרְמוֹס", note: "Rambam: 'wild lupine'; the counterpart of turmos." },
      identification: { binomial: "Lupinus luteus", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks: yellow lupine (L. luteus), the wild counterpart. Genus secure; exact wild species open.", badge: "lexicon" },
      etymology_latin: { Lupinus: "Latin 'of the wolf' (lupus).", luteus: "Latin 'golden-yellow', for the flowers." },
      kilayim: [{ with: "turmos", ruling: "not_kilayim", ref: "Kilayim 1:3" }],
      rambam: "plaslos",
    },

    /* ---- tranche 4: the fruit trees of Kilayim 1:4 (the family-analysis payoff) ---- */
    {
      id: "agasim", chapter: 1, mishnah_ref: "1:4",
      names: { he: "אֲגָסִים", translit: "agasim", en: ["pear"] },
      pair: { id: "krustumelin", he: "קְרֻסְתּוּמֵלִין", note: "Paired not-kilayim with the Crustumian pear." },
      identification: { binomial: "Pyrus communis", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks; Löw. Rambam Arabic kummathra (cultivated pear).", badge: "lexicon" },
      etymology_latin: { Pyrus: "Latin 'pirus/pyrus', the pear tree.", communis: "Latin 'common', the widely cultivated species." },
      kilayim: [{ with: "krustumelin", ruling: "not_kilayim", ref: "Kilayim 1:4" }],
      rambam: "agasim",
    },
    {
      id: "krustumelin", chapter: 1, mishnah_ref: "1:4",
      names: { he: "קְרֻסְתּוּמֵלִין", translit: "kerustumelin", en: ["Crustumian pear"] },
      pair: { id: "agasim", he: "אֲגָסִים", note: "A Roman cultivar of the common pear — same species as agasim." },
      identification: { binomial: "Pyrus communis", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks/Löw: Pliny's 'crustumina' pear (Nat. Hist. 15:53), a cultivar of Pyrus communis — not a distinct species.", badge: "lexicon" },
      etymology_latin: { Pyrus: "Latin, the pear tree.", communis: "Latin 'common'; this named cultivar (Crustumina, from the town Crustumerium) belongs to it." },
      kilayim: [{ with: "agasim", ruling: "not_kilayim", ref: "Kilayim 1:4" }],
      rambam: "krustumelin",
    },
    {
      id: "perishim", chapter: 1, mishnah_ref: "1:4",
      names: { he: "פְּרִישִׁים", translit: "perishim", en: ["quince"] },
      pair: { id: "uzradim", he: "עֻזְרָדִים", note: "Different genus from azarole, same family Rosaceae — yet not kilayim." },
      identification: { binomial: "Cydonia oblonga", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks/Löw. Rambam Arabic safarjal (quince). Cydonia is monotypic.", badge: "lexicon" },
      etymology_latin: { Cydonia: "Latin '(mala) Cydonia', apples of Kydonia (Chania, Crete).", oblonga: "Latin 'oblong', for the elongated fruit." },
      kilayim: [{ with: "uzradim", ruling: "not_kilayim", ref: "Kilayim 1:4" }],
      rambam: "perishim",
    },
    {
      id: "uzradim", chapter: 1, mishnah_ref: "1:4",
      names: { he: "עֻזְרָדִים", translit: "uzradim", en: ["azarole", "Mediterranean medlar"] },
      pair: { id: "perishim", he: "פְּרִישִׁים", note: "Crataegus; different genus from quince (Cydonia), same family — not kilayim." },
      identification: { binomial: "Crataegus azarolus", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks/Löw. Rambam Arabic al-zu'rur (azarole hawthorn).", badge: "lexicon" },
      etymology_latin: { Crataegus: "Greek 'kratos' (strength, hard wood) + 'akis' (thorn).", azarolus: "Latinized from Arabic al-zu'rur, the azarole fruit." },
      kilayim: [{ with: "perishim", ruling: "not_kilayim", ref: "Kilayim 1:4" }],
      rambam: "uzradim",
    },
    {
      id: "tapuach", chapter: 1, mishnah_ref: "1:4",
      names: { he: "תַּפּוּחַ", translit: "tapuach", en: ["apple"] },
      pair: { id: "chazrad", he: "חַזְרָד", note: "Kilayim despite resemblance — same family Rosaceae, different genera." },
      identification: { binomial: "Malus domestica", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks. Rambam Arabic tuffah (apple). Malus domestica is the conserved name.", badge: "lexicon" },
      etymology_latin: { Malus: "Latin 'apple tree', from Greek 'melon' (apple).", domestica: "Latin 'of the household, cultivated'." },
      kilayim: [{ with: "chazrad", ruling: "kilayim", ref: "Kilayim 1:4", note: "'Even though they resemble each other, they are kilayim.'" }],
      rambam: null,
    },
    {
      id: "chazrad", chapter: 1, mishnah_ref: "1:4",
      names: { he: "חַזְרָד", translit: "chazrad", en: ["Syrian pear (Feliks) / sorb-azarole (Rambam)"] },
      pair: { id: "tapuach", he: "תַּפּוּחַ", note: "Kilayim with apple (1:4)." },
      identification: { binomial: "Pyrus syriaca", family: "Rosaceae", confidence: "disputed",
        id_source: "GENUINE DISPUTE: Feliks/Löw = wild Syrian pear (Pyrus syriaca). Rambam's 'al-azaron' reading makes it azarole/sorb (Crataegus/Sorbus), overlapping uzradim.", badge: "lexicon" },
      etymology_latin: { Pyrus: "Latin, the pear tree.", syriaca: "Latin 'Syrian', for the Levantine range." },
      kilayim: [{ with: "tapuach", ruling: "kilayim", ref: "Kilayim 1:4" }],
      rambam: "chazrad",
      note_ambiguous: "ID disputed (Syrian pear vs azarole); this affects whether the apple-pair is same-family or shares a genus with uzradim.",
    },
    {
      id: "parskim", chapter: 1, mishnah_ref: "1:4",
      names: { he: "פַּרְסְקִים", translit: "parsekim", en: ["peach"] },
      pair: { id: "shkedin", he: "שְׁקֵדִין", note: "Kilayim with almond — YET both are the same genus, Prunus (they even hybridize)." },
      identification: { binomial: "Prunus persica", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks/Löw. Rambam Arabic al-khawkh (peach).", badge: "lexicon" },
      etymology_latin: { Prunus: "Latin 'plum tree', from Greek 'proumnon', the stone-fruit genus.", persica: "Latin 'Persian' (malum Persicum, 'Persian apple')." },
      kilayim: [{ with: "shkedin", ruling: "kilayim", ref: "Kilayim 1:4", note: "Same genus Prunus, yet ruled kilayim — halacha finer than botany." }],
      rambam: "parskim",
    },
    {
      id: "shkedin", chapter: 1, mishnah_ref: "1:4",
      names: { he: "שְׁקֵדִין", translit: "shekedin", en: ["almond"] },
      pair: { id: "parskim", he: "פַּרְסְקִים", note: "Same genus as peach (Prunus), yet kilayim." },
      identification: { binomial: "Prunus dulcis", family: "Rosaceae", confidence: "settled",
        id_source: "Feliks. Rambam Arabic al-luz (almond). Accepted name Prunus dulcis (syn. Amygdalus communis).", badge: "lexicon" },
      etymology_latin: { Prunus: "Latin 'plum tree', the stone-fruit genus.", dulcis: "Latin 'sweet', vs the bitter almond." },
      kilayim: [{ with: "parskim", ruling: "kilayim", ref: "Kilayim 1:4" }],
      rambam: "shkedin",
    },
    {
      id: "shizafin", chapter: 1, mishnah_ref: "1:4",
      names: { he: "שִׁזָּפִין", translit: "shizzafin", en: ["jujube"] },
      pair: { id: "rimin", he: "רִימִין", note: "Kilayim with the nabk-jujube — YET both are the same genus, Ziziphus." },
      identification: { binomial: "Ziziphus jujuba", family: "Rhamnaceae", confidence: "disputed",
        id_source: "Feliks/Amar = jujube (Ziziphus jujuba). Rambam gives no gloss here.", badge: "lexicon" },
      etymology_latin: { Ziziphus: "Latinized from Persian zizfum (via Greek zizyphon), the jujube.", jujuba: "Medieval Latin variant of zizyphum, the jujube fruit." },
      kilayim: [{ with: "rimin", ruling: "kilayim", ref: "Kilayim 1:4", note: "Same genus Ziziphus, yet kilayim." }],
      rambam: null,
    },
    {
      id: "rimin", chapter: 1, mishnah_ref: "1:4",
      names: { he: "רִימִין", translit: "rimin", en: ["Christ's-thorn jujube", "nabk"] },
      pair: { id: "shizafin", he: "שִׁזָּפִין", note: "Same genus as shizafin (Ziziphus), yet kilayim. NOT pomegranate (rimon)." },
      identification: { binomial: "Ziziphus spina-christi", family: "Rhamnaceae", confidence: "disputed",
        id_source: "Feliks/Amar = Z. spina-christi. Rambam Arabic al-nabk (jujube). Nabk/sidr is shared with Z. lotus; some conflate.", badge: "lexicon" },
      etymology_latin: { Ziziphus: "Latinized from Persian zizfum, the jujube.", "spina-christi": "Latin 'thorn of Christ', from the crown-of-thorns tradition." },
      kilayim: [{ with: "shizafin", ruling: "kilayim", ref: "Kilayim 1:4" }],
      rambam: "rimin",
      note_ambiguous: "Not the pomegranate (rimon); a Ziziphus.",
    },

    /* ---- tranche 5: Kilayim 1:5 (kilayim despite resemblance) ---- */
    {
      id: "tzenon", chapter: 1, mishnah_ref: "1:5",
      names: { he: "צְנוֹן", translit: "tzenon", en: ["radish"] },
      pair: { id: "nafutz", he: "נָפוּץ", note: "Kilayim with nafutz despite resemblance (1:5)." },
      identification: { binomial: "Raphanus sativus", family: "Brassicaceae", confidence: "settled",
        id_source: "Feliks; Amar; Rambam Arabic fijl (radish).", badge: "lexicon" },
      etymology_latin: { Raphanus: "Latin from Greek 'rhaphanos', the radish.", sativus: "Latin 'cultivated, sown'." },
      kilayim: [{ with: "nafutz", ruling: "kilayim", ref: "Kilayim 1:5" }],
      rambam: null,
    },
    {
      id: "lafsan", chapter: 1, mishnah_ref: "1:5",
      names: { he: "לַפְסָן", translit: "lafsan", en: ["charlock", "wild mustard"] },
      pair: { id: "chardal", he: "חַרְדָּל", note: "Kilayim with black mustard (1:5) though both partners are genus Sinapis-adjacent — halacha by resemblance." },
      identification: { binomial: "Sinapis arvensis", family: "Brassicaceae", confidence: "disputed",
        id_source: "Feliks; Amar: charlock/wild mustard (S. arvensis). Rambam: a turnip-flavored plant the physicians call 'lafsin'.", badge: "lexicon" },
      etymology_latin: { Sinapis: "Latin/Greek 'sinapi', mustard.", arvensis: "Latin 'of cultivated fields', from 'arvum'." },
      kilayim: [{ with: "chardal", ruling: "kilayim", ref: "Kilayim 1:5" }],
      rambam: "lafsan",
    },
    {
      id: "delaat-yevanit", chapter: 1, mishnah_ref: "1:5",
      names: { he: "דְּלַעַת יְוָנִית", translit: "dela'at yevanit", en: ["Grecian gourd", "bottle gourd"] },
      pair: { id: "delaat-hamitzri", he: "דְּלַעַת הַמִּצְרִי", note: "Kilayim with the Egyptian & remutzah gourds (1:5) despite resemblance." },
      identification: { binomial: "Lagenaria siceraria", family: "Cucurbitaceae", confidence: "settled",
        id_source: "Feliks: the Grecian gourd = Lagenaria siceraria, distinguished in 1:5 from the Egyptian gourd.", badge: "lexicon" },
      etymology_latin: { Lagenaria: "Latin 'lagena' (flask), for the bottle-shaped fruit.", siceraria: "Latin 'sicera' (strong drink), for its use as a drink vessel." },
      kilayim: [{ with: "delaat-hamitzri", ruling: "kilayim", ref: "Kilayim 1:5" }],
      rambam: null,
    },

    /* ---- tranche 6: Kilayim 1:8 — grafting / yerek-b'ilan context (no min-pair) ---- */
    {
      id: "shikma", chapter: 1, mishnah_ref: "1:8",
      names: { he: "שִׁקְמָה", translit: "shikmah", en: ["sycamore fig", "fig-mulberry"] },
      pair: null,
      identification: { binomial: "Ficus sycomorus", family: "Moraceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic jummayz. Hebrew shiqmah likely underlies the Greek name.", badge: "lexicon" },
      etymology_latin: { Ficus: "Latin, the fig tree.", sycomorus: "Greek 'sykomoros' (fig-mulberry), sykon (fig) + moron (mulberry)." },
      kilayim: [],
      rambam: "shikma",
      note_context: "1:8: one may not plant vegetables into a sycamore stump (yerek b'ilan).",
    },
    {
      id: "peigam", chapter: 1, mishnah_ref: "1:8",
      names: { he: "פֵּיגָם", translit: "peigam", en: ["rue"] },
      pair: null,
      identification: { binomial: "Ruta chalepensis", family: "Rutaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam gives the Arabic/laaz. Greek peganon underlies the name.", badge: "lexicon" },
      etymology_latin: { Ruta: "Latin 'ruta', from Greek 'rhytē', the rue.", chalepensis: "Latin 'of Aleppo' (Chalepum), with -ensis (belonging to a place)." },
      kilayim: [],
      rambam: "peigam",
      note_context: "1:8: one may not graft rue on white cassia (a vegetable on a tree).",
    },
    {
      id: "kida-levana", chapter: 1, mishnah_ref: "1:8",
      names: { he: "קִדָּה לְבָנָה", translit: "kiddah levanah", en: ["white cassia"] },
      pair: null,
      identification: { binomial: "Cinnamomum", family: "Lauraceae", confidence: "conjectural",
        id_source: "Traditionally cassia (Cinnamomum), a ketores spice; Rambam calls it a fragrant tree; Feliks/Amar note the identity is unsettled, and 'levana' complicates it.", badge: "lexicon" },
      etymology_latin: { Cinnamomum: "Latinized Greek 'kinnamomon', of Semitic/Phoenician origin, the aromatic bark." },
      kilayim: [],
      rambam: "kida_levana",
      note_ambiguous: "Identity unsettled; Rambam glosses it only as a fragrant tree.",
    },
    {
      id: "teena", chapter: 1, mishnah_ref: "1:8",
      names: { he: "תְּאֵנָה", translit: "te'enah", en: ["fig", "common fig"] },
      pair: null,
      identification: { binomial: "Ficus carica", family: "Moraceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic tin (fig). Universal.", badge: "lexicon" },
      etymology_latin: { Ficus: "Latin, the fig tree.", carica: "Latin, of Caria (Asia Minor), famed for figs." },
      kilayim: [],
      rambam: null,
      note_context: "1:8 (grafting a fig shoot into a squill); also 6:5 (a fruit tree, not an ilan srak).",
    },
    {
      id: "chatzuv", chapter: 1, mishnah_ref: "1:8",
      names: { he: "חֲצוּב", translit: "chatzuv", en: ["squill", "sea squill"] },
      pair: null,
      identification: { binomial: "Drimia maritima", family: "Asparagaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic 'unsul. Formerly Urginea/Scilla maritima. Famed as a field-boundary marker.", badge: "lexicon" },
      etymology_latin: { Drimia: "Greek 'drimys' (acrid), for the irritant sap.", maritima: "Latin 'of the sea', for the coastal habitat." },
      kilayim: [],
      rambam: "chatzuv",
      note_context: "1:8: its deep straight roots (which Yehoshua used to mark tribal borders) resist grafting.",
    },
    {
      id: "gefen", chapter: 1, mishnah_ref: "1:8",
      names: { he: "גֶּפֶן", translit: "gefen", en: ["grapevine", "grape"] },
      pair: null,
      identification: { binomial: "Vitis vinifera", family: "Vitaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic karm/'inab. Universal.", badge: "lexicon" },
      etymology_latin: { Vitis: "Latin 'vine', related to 'viere' (to twist).", vinifera: "Latin 'wine-bearing' (vinum + ferre)." },
      kilayim: [],
      rambam: null,
      note_context: "The vine is central to kilei hakerem (chs. 4-7); it recurs throughout the masechta.",
    },
    {
      id: "avatiach", chapter: 1, mishnah_ref: "1:8",
      names: { he: "אֲבַטִּיחַ", translit: "avatiach", en: ["watermelon"] },
      pair: null,
      identification: { binomial: "Citrullus lanatus", family: "Cucurbitaceae", confidence: "disputed",
        id_source: "Feliks & mainstream: watermelon (Citrullus lanatus). The Palestinian Targum instead equates avatiach with muskmelon; Feliks rejects this. Rambam laaz al-battikh.", badge: "lexicon" },
      etymology_latin: { Citrullus: "Diminutive of Latin 'citrus' (citron), for the smaller gourd.", lanatus: "Latin 'woolly' (lana), for the young plant's down." },
      kilayim: [],
      rambam: "avatiach",
      note_context: "1:8: one may not thrust a vine-shoot into a watermelon (ilan b'yerek).",
    },
    {
      id: "delaat", chapter: 1, mishnah_ref: "1:8",
      names: { he: "דְּלַעַת", translit: "dela'at", en: ["bottle gourd", "gourd"] },
      pair: null,
      identification: { binomial: "Lagenaria siceraria", family: "Cucurbitaceae", confidence: "settled",
        id_source: "Feliks: the generic dela'at is the Lagenaria bottle gourd (the 'Grecian gourd' of 1:5).", badge: "lexicon" },
      etymology_latin: { Lagenaria: "Latin 'lagena' (flask).", siceraria: "Latin 'sicera' (strong drink)." },
      kilayim: [],
      rambam: null,
      note_context: "Recurs in the garden-bed and grafting mishnayot (1:8, 3:4-7).",
    },
    {
      id: "chalamit", chapter: 1, mishnah_ref: "1:8",
      names: { he: "חַלָּמִית", translit: "chalamit", en: ["mallow", "cheeseweed"] },
      pair: null,
      identification: { binomial: "Malva parviflora", family: "Malvaceae", confidence: "disputed",
        id_source: "Feliks/Amar favor M. parviflora (the edible Levantine khubeza). Rambam: 'a vegetable whose meaning we do not know', tentatively a mallow. Species not fixed.", badge: "lexicon" },
      etymology_latin: { Malva: "Latin, from Greek 'malache/malakos' (soft), for the mucilaginous emollient.", parviflora: "Latin 'small-flowered' (parvus + flos)." },
      kilayim: [],
      rambam: "chalamit",
      note_context: "1:8: one may not set gourd seed into a mallow to preserve it (yerek b'yerek).",
    },

    /* ---- tranche 7: plants first named in Kilayim chapters 2-9 ---- */
    {
      id: "pishtan", chapter: 9, mishnah_ref: "9:1",
      names: { he: "פִּשְׁתָּן", translit: "pishtan", en: ["flax", "linseed"] },
      pair: null,
      identification: { binomial: "Linum usitatissimum", family: "Linaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam: 'shesh' is flax. Universal.", badge: "lexicon" },
      etymology_latin: { Linum: "Classical Latin for flax/linen (Greek 'linon').", usitatissimum: "Latin superlative 'most useful', for its many uses." },
      kilayim: [],
      rambam: "pishtan",
      note_context: "The type-plant of kilei begadim (sha'atnez): flax with wool is the only fabric kilayim (9:1).",
    },
    {
      id: "kanbos", chapter: 2, mishnah_ref: "2:5",
      names: { he: "קַנְבּוֹס", translit: "kanbos", en: ["hemp"] },
      pair: null,
      identification: { binomial: "Cannabis sativa", family: "Cannabaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic al-qanab. Hebrew kanbos is cognate with the Greek/Latin name.", badge: "lexicon" },
      etymology_latin: { Cannabis: "Latin from Greek 'kannabis', an old loan for hemp; cognate with kanbos.", sativa: "Latin 'sown, cultivated'." },
      kilayim: [],
      rambam: "kanbos",
      note_context: "2:5 (a 3-year field crop); 5:8 (kilayim in the vineyard? — machlokes R' Tarfon/Chachamim); 9:1/9:7 (its threads resemble linen).",
    },
    {
      id: "luf", chapter: 2, mishnah_ref: "2:5",
      names: { he: "לוּף", translit: "luf", en: ["arum", "Palestine arum"] },
      pair: null,
      identification: { binomial: "Arum palaestinum", family: "Araceae", confidence: "disputed",
        id_source: "GENUINE DISPUTE: modern consensus (Feliks, Albeck) = Arum palaestinum (Araceae geophyte); Rambam & several rishonim describe luf as a kind of onion/bulb crop.", badge: "lexicon" },
      etymology_latin: { Arum: "Latinized Greek 'aron', the cuckoo-pint/arum.", palaestinum: "Latin 'of Palestine', for its native range." },
      kilayim: [],
      rambam: "luf",
      note_ambiguous: "Arum (Feliks) vs an onion-type (Rambam) — a real genus-level dispute.",
      note_context: "2:5: a field crop that regrows for three years.",
    },
    {
      id: "istis", chapter: 2, mishnah_ref: "2:5",
      names: { he: "אִסְטִיס", translit: "istis", en: ["woad", "dyer's woad"] },
      pair: null,
      identification: { binomial: "Isatis tinctoria", family: "Brassicaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam: the blue-dye plant (indigo-type).", badge: "lexicon" },
      etymology_latin: { Isatis: "Greek 'isatis', the ancient name for woad.", tinctoria: "Latin 'of dyers' (tingere, to dye), for the blue dye." },
      kilayim: [],
      rambam: "istis",
      note_context: "2:5: appears as self-seeding aftergrowth (sefichim) in a grain field.",
    },
    {
      id: "tiltan", chapter: 2, mishnah_ref: "2:5",
      names: { he: "תִּלְתָּן", translit: "tiltan", en: ["fenugreek", "Greek hay"] },
      pair: null,
      identification: { binomial: "Trigonella foenum-graecum", family: "Fabaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic hulba (fenugreek). (Modern Hebrew tiltan = clover; the Mishnaic plant is fenugreek.)", badge: "lexicon" },
      etymology_latin: { Trigonella: "Greek 'little triangle', for the triangular flower.", "foenum-graecum": "Latin 'Greek hay', for its use as fodder." },
      kilayim: [],
      rambam: "tiltan",
      note_context: "2:5: sown for human food in tidy patches; example of intentional cultivation.",
    },
    {
      id: "charia", chapter: 2, mishnah_ref: "2:8",
      names: { he: "חָרִיעַ", translit: "charia", en: ["safflower", "false saffron"] },
      pair: null,
      identification: { binomial: "Carthamus tinctorius", family: "Asteraceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw. Talmudic kurtama/morika = safflower; Rambam laaz 'usfur.", badge: "lexicon" },
      etymology_latin: { Carthamus: "From Arabic 'qurtum' / Syriac 'qurtema', safflower (a root meaning 'to cut/trim').", tinctorius: "Latin 'of dyers' (tingere), for the floret dye." },
      kilayim: [],
      rambam: "charia",
      note_context: "2:8: paired with mustard as a crop that damages grain, so kept apart. NB 'qurtum' is the Arabic behind Rambam's anomalous gloss on tofeach.",
    },
    {
      id: "afunim-shufin", chapter: 3, mishnah_ref: "3:2",
      names: { he: "אֲפוּנִים הַשּׁוּפִין", translit: "afunim ha-shufin", en: ["chickpea (smooth grade)"] },
      pair: { id: "afunim-gamlanim", he: "אֲפוּנִים הַגַּמְלָנִים", note: "The smooth/small grade, paired with the large 'camel' grade." },
      identification: { binomial: "Cicer arietinum", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks: chickpea (a summer crop, per 3:2). Rambam-anchor & modern Hebrew read afunim as garden pea (Pisum sativum). Genus is the disputed axis.", badge: "lexicon" },
      etymology_latin: { Cicer: "Classical Latin for the chickpea.", arietinum: "Latin 'of a ram' (aries), the seed's ram's-head shape." },
      kilayim: [],
      rambam: "afunim_shufin",
      note_context: "3:2: classed as a 'seed crop' (not a garden vegetable) for the garden-bed rules.",
    },
    {
      id: "afunim-gamlanim", chapter: 3, mishnah_ref: "3:2",
      names: { he: "אֲפוּנִים הַגַּמְלָנִים", translit: "afunim ha-gamlanim", en: ["chickpea (large grade)"] },
      pair: { id: "afunim-shufin", he: "אֲפוּנִים הַשּׁוּפִין", note: "The large 'camel' grade (gamal = camel)." },
      identification: { binomial: "Cicer arietinum", family: "Fabaceae", confidence: "disputed",
        id_source: "Feliks: large-grade chickpea. Rambam-anchor: large pea (Pisum sativum). Genus disputed (Cicer vs Pisum).", badge: "lexicon" },
      etymology_latin: { Cicer: "Classical Latin for the chickpea.", arietinum: "Latin 'of a ram', the seed's shape." },
      kilayim: [],
      rambam: "afunim_gamlanim",
      note_context: "3:2: classed as a 'garden vegetable' (unlike the smooth grade), so treated differently in the arugah.",
    },
    {
      id: "zayit", chapter: 6, mishnah_ref: "6:5",
      names: { he: "זַיִת", translit: "zayit", en: ["olive"] },
      pair: null,
      identification: { binomial: "Olea europaea", family: "Oleaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam Arabic zaytun. Universal.", badge: "lexicon" },
      etymology_latin: { Olea: "Latin 'olive tree', from Greek 'elaia'.", europaea: "Latin 'European', for the Mediterranean range." },
      kilayim: [],
      rambam: null,
      note_context: "6:5: R' Meir names the olive and fig as the paradigm fruit trees (not 'ilan srak').",
    },
    {
      id: "irus", chapter: 5, mishnah_ref: "5:8",
      names: { he: "אִירוּס", translit: "irus", en: ["iris", "flag"] },
      pair: null,
      identification: { binomial: "Iris", family: "Iridaceae", confidence: "disputed",
        id_source: "Feliks; Amar: an Iris (genus level; I. palaestina often cited). The Hebrew irus itself underlies the botanical name. Rambam gives a different laaz (a mint/broad-leafed herb).", badge: "lexicon" },
      etymology_latin: { Iris: "Greek 'iris' (rainbow), for the varied flower colours." },
      kilayim: [],
      rambam: "irus",
      note_context: "5:8: an ornamental that is not kilayim in the vineyard (people don't grow it as a crop there).",
    },
    {
      id: "kissom", chapter: 5, mishnah_ref: "5:8",
      names: { he: "קִסּוֹם", translit: "kissom", en: ["ivy"] },
      pair: null,
      identification: { binomial: "Hedera helix", family: "Araliaceae", confidence: "settled",
        id_source: "Feliks; Amar; Löw; Rambam laaz. Greek 'kissos' (ivy) underlies the Hebrew.", badge: "lexicon" },
      etymology_latin: { Hedera: "Latin, the classical name for ivy (perh. 'haerere', to cling).", helix: "Greek 'helix' (spiral), for the twining growth." },
      kilayim: [],
      rambam: "kissom",
      note_context: "5:8: listed with the iris and lily as not kilayim in the vineyard.",
    },
    {
      id: "shoshanat-hamelech", chapter: 5, mishnah_ref: "5:8",
      names: { he: "שׁוֹשַׁנַּת הַמֶּלֶךְ", translit: "shoshanat ha-melech", en: ["Madonna lily", "king's lily"] },
      pair: null,
      identification: { binomial: "Lilium candidum", family: "Liliaceae", confidence: "disputed",
        id_source: "Feliks; Amar favor Lilium candidum (white Madonna lily). 'Shoshana' is ambiguous (also proposed: Narcissus, a water-lily). Rambam laaz shaqa'iq al-nu'man.", badge: "lexicon" },
      etymology_latin: { Lilium: "Latin 'lily', from Greek 'leirion' (Eastern origin).", candidum: "Latin 'pure white', for the flower." },
      kilayim: [],
      rambam: "shoshanat_hamelech",
      note_ambiguous: "Madonna-lily reading is favored but not unanimous (shoshana is ambiguous).",
      note_context: "5:8: not kilayim in the vineyard.",
    },
    {
      id: "kinras", chapter: 5, mishnah_ref: "5:8",
      names: { he: "קִנְרָס", translit: "kinras", en: ["artichoke", "cardoon"] },
      pair: null,
      identification: { binomial: "Cynara cardunculus", family: "Asteraceae", confidence: "disputed",
        id_source: "Feliks; Amar: Cynara (Hebrew קנרס = Latin cynara). Globe artichoke vs cardoon is unsettled; the ancestral C. cardunculus covers both. Rambam laaz al-qanariya.", badge: "lexicon" },
      etymology_latin: { Cynara: "Latinized Greek 'kynara/kinara', the artichoke; cognate with Hebrew kinras.", cardunculus: "Latin diminutive of 'carduus' (thistle), 'little thistle'." },
      kilayim: [],
      rambam: "kinras",
      note_context: "5:8: unlike the iris/ivy/lily, the artichoke IS kilayim in the vineyard (it is grown as a crop).",
    },
    {
      id: "kotzim", chapter: 5, mishnah_ref: "5:8",
      names: { he: "קוֹצִים", translit: "kotzim", en: ["thorns", "thistles"] },
      pair: null,
      identification: { binomial: "Ononis", family: "Fabaceae", confidence: "conjectural",
        id_source: "A GENERIC term for thorny plants, not one species. Feliks/Löw cite candidates (Ononis restharrow; also Sarcopoterium, thistles). Rambam: a general category (Arabic shawk).", badge: "descript" },
      etymology_latin: { Ononis: "Latinized Greek 'ononis', restharrow (one representative thorny genus)." },
      kilayim: [],
      rambam: null,
      note_ambiguous: "Generic 'thorns' — no single species; one representative given (Ononis).",
      note_context: "5:8: R' Eliezer vs Chachamim on whether keeping thorns in a vineyard sanctifies it (only in Arabia, where thorns are grown as camel fodder).",
    },
    {
      id: "zered", chapter: 9, mishnah_ref: "9:7",
      names: { he: "זֶרֶד", translit: "zered", en: ["zered (a plant-fiber for footwear)"] },
      pair: null,
      identification: { binomial: "(uncertain)", family: "(uncertain)", confidence: "conjectural",
        id_source: "A plant-material used for a soft under-shoe; not a food/fabric kilayim. The specific plant is unidentified in the sources; Rambam describes only the footwear, not the plant.", badge: "descript" },
      etymology_latin: {},
      kilayim: [],
      rambam: "zered",
      note_ambiguous: "Ambiguous — a plant-fiber shoe, exempt from kilayim (9:7); the plant itself is not identified.",
    },
  ],
};
